### ISSUE TITLE
GTG 0.3.1-1 does not launch in Ubuntu 14.04

### ISSUE THREAD

**Issue by jakubbrindza** [getting-things-gnome/gtg#100]
THIS IS A REFERENCED BUG FROM LAUNCHPAD. 
DESCRIPTION BELOW. 
FOR FULL CONVERSATION, LOOK AT https://bugs.launchpad.net/gtg/+bug/1383105

GTG 0.3.1-1 does not launch in Ubuntu 14.04. When I launched gtg in teminal, I get the following messages.
Please help.

~$ gtg
2014-10-20 11:40:40,692 - WARNING - **init**:**init**:74 - Backend backend_evolution could not be loaded: No module named evolution
Traceback (most recent call last):
  File "/usr/bin/gtg", line 89, in <module>
    main()
  File "/usr/bin/gtg", line 85, in main
    sys.exit(gtg.main(options, args))
  File "/usr/share/gtg/GTG/gtg.py", line 121, in main
    ds, req = core_main_init(options, args)
  File "/usr/share/gtg/GTG/gtg.py", line 149, in core_main_init
    backends_list = BackendFactory().get_saved_backends_list()
  File "/usr/share/gtg/GTG/backends/**init**.py", line 174, in get_saved_backends_list
    self.restore_backend_from_xml(dic)
  File "/usr/share/gtg/GTG/backends/**init**.py", line 158, in restore_backend_from_xml
    dic["backend"] = module.Backend(dic)
  File "/usr/share/gtg/GTG/backends/backend_localfile.py", line 100, in **init**
    cleanxml.savexml(self.get_path(), self.doc, backup=True)
  File "/usr/share/gtg/GTG/tools/cleanxml.py", line 197, in savexml
    os.rename(zefile, tmpfile)
OSError: [Errno 13] Permission denied
~$

**Comment by izidormatusov** [comment]
We can provide a check if the user has permissions to read/write every time tasks are save.

In ideal case, there would be a clear error message provided instead.

**Comment by nekohayo** [comment]
Reopen if still an issue with current git master of everything.
