### ISSUE TITLE
CalDav: VTODO without CREATED field corrupts the xml store

### ISSUE THREAD

**Issue by picsel2** [getting-things-gnome/gtg#1033]
## Failure description

GTG (master) crashes at startup.

**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/GTG/gtk/application.py", line 115, in do_startup
    self.ds.find_and_load_file(data_file)
  File "/app/lib/python3.11/site-packages/GTG/core/datastore.py", line 407, in find_and_load_file
    self.load_file(filepath)
  File "/app/lib/python3.11/site-packages/GTG/core/datastore.py", line 109, in load_file
    self.load_data(self.xml_tree)
  File "/app/lib/python3.11/site-packages/GTG/core/datastore.py", line 92, in load_data
    self.tasks.from_xml(data.find('tasklist'), self.tags)
  File "/app/lib/python3.11/site-packages/GTG/core/tasks.py", line 780, in from_xml
    added = dates.find('added').text
            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

**Software versions:**
* Getting Things GNOME! 0.6.0
* CPython 3.11.7 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0]
* GTK 4.12.5, GLib 2.78.4
* PyGLib 3.46.0, PyGObject 3.46.0
* Linux-6.7.5-200.fc39.x86_64-x86_64-with-glibc2.38
* Flatpak 1.15.6
* Flatpak runtime: runtime/org.gnome.Platform/x86_64/45 (57d12cbe72e28d786a210eced336f3ebcd99a229dd6dc1d55917cb9efb1ffa7d)
* Flatpak app: org.gnome.GTGDevel (e327307520d14e896a85005d21d346e3c7317fa94a671e1a7c93ab57f923ffe9)

## Source of failure

Syncing a task that has no CREATED field leads to a state where the task's 'date_added' attribute is not set.
The xml task element that is subsequently written to disk has then no `added` tag, although the schema requires it to be always present.

## Examples

Content of an ical file without `CREATED` field (this VTODO was created by Nextcloud Deck):
```
BEGIN:VCALENDAR
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
METHOD:PUBLISH
BEGIN:VTODO
DTSTAMP:20231121T193352Z
UID:deck-card-986
RELATED-TO:deck-stack-83
STATUS:NEEDS-ACTION
SUMMARY:Sturm des Wissens – Rostocks Netzwerk für Wissenschaft\, 
 Wirtschaft\, Politik und Bildung
DESCRIPTION:https://rostock365.de/sturm-des-wissens/
X-EVOLUTION-CALDAV-ETAG:b00f4accffd2039b526643f421925b48
END:VTODO
END:VCALENDAR
```

Resulting xml element where the `added` tag is missing:
```xml
<task id="deck-card-986" status="Active" uuid="deck-card-986" recurring="False">
      <tags>
        <tag>3f3ab74c-5f52-4566-b62c-cc76bcc7d06a</tag>
      </tags>
      <title>Sturm des Wissens – Rostocks Netzwerk für Wissenschaft, Wirtschaft, Politik und Bildung</title>
      <dates>
        <modified>2023-11-08 14:14:27.529767</modified>
      </dates>
      <recurring enabled="false">
        <term>None</term>
        <updated_date>9999-12-30</updated_date>
      </recurring>
      <subtasks/>
      <content><![CDATA[@Deck:_GTD

https://rostock365.de/sturm-des-wissens/]]></content>
    </task>
```

**Comment by pentux-GitHub** [comment]
Status: both halves of this bug are now covered.

**Prevention** (no store can be written without an added date anymore)
landed with #1265: `fill_task` falls back on `date_modified` when a
VTODO has no CREATED field (`backend_caldav.py:1143-1150`). The unit
test `test_import_todo_without_created_date` pins it, and it covers the
exact Nextcloud Deck VTODO from this report — no CREATED, no
LAST-MODIFIED, non-UUID UID.

**Healing** (stores already damaged while the bug was live) is #1298:
`from_xml` no longer asserts on a missing or empty `<added>` element,
it falls back on the modification date with a warning. Red-before /
green-after against both corruption forms. The 0.6 migration path
already had its own fallback in `versioning.py`.

Merging #1298 closes this.
