### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_id' when syncing CalDAV

### ISSUE THREAD

**Issue by cpitclaudel** [getting-things-gnome/gtg#1057]
I'm trying to setup CalDAV sync, and I got the following issue:

```
2024-03-07 07:55:30,052 - INFO - backend_caldav:_do_periodic_import:137 - Running periodic import
2024-03-07 07:55:30,237 - INFO - backend_caldav:_do_periodic_import:144 - Fetching todos from '<redacted-1>'
2024-03-07 07:55:30,714 - INFO - backend_caldav:_do_periodic_import:144 - Fetching todos from '<redacted-2>'
Exception in thread Thread-3 (_internal_flush_all_tasks):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
2024-03-07 07:55:31,120 - INFO - backend_caldav:_do_periodic_import:137 - Running periodic import
    self._target(*self._args, **self._kwargs)
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/core/datastore.py", line 664, in _internal_flush_all_tasks
    backend.queue_set_task(task.id)
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/generic_backend.py", line 680, in queue_set_task
    tid = task.get_id()
AttributeError: 'str' object has no attribute 'get_id'
```

I added a `print(task)` right before the faulty line, and I got:

```
33d9760d-2e07-4ae4-9c02-1fcdaeb46325
```

This is the faulty function:

```
    def queue_set_task(self, task):
        """ Save the task in the backend. In particular, it just enqueues the
        task in the self.to_set queue. A thread will shortly run to apply the
        requested changes.

        @param task: the task that should be saved
        """
        tid = task.get_id()
        if task not in self.to_set and tid not in self.to_remove:
            self.to_set.appendleft(task)
            self.__try_launch_setting_thread()
```

Looks like a simple mistake in the caller?

```
        def _internal_flush_all_tasks():
            backend = self.backends[backend_id]
            for task in self.tasks.data:
                if self.please_quit:
                    break
                backend.queue_set_task(task.id) # ← Should be `task`?
```

Except that `Task` objects don't have a `get_id`, they have `.id`.  After fixing that too I get a bit further in the import before getting to another crash, though in the DAV client this time.

```
Exception in thread Thread-1 (__backend_startup):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/core/datastore.py", line 579, in __backend_startup
    backend.start_get_tasks()
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/periodic_import_backend.py", line 79, in start_get_tasks
    self._start_get_tasks()
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/periodic_import_backend.py", line 98, in _start_get_tasks
    self.do_periodic_import()
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/backend_caldav.py", line 111, in do_periodic_import
    self._do_periodic_import()
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/backend_caldav.py", line 139, in _do_periodic_import
    self._refresh_calendar_list()
  File "/home/cpc/git/gtg/.local_build/install/local/lib/python3.10/dist-packages/GTG/backends/backend_caldav.py", line 217, in _refresh_calendar_list
    principal = self._dav_client.principal()
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/davclient.py", line 425, in principal
    self._principal = Principal(client=self, *largs, **kwargs)
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/objects.py", line 506, in __init__
    cup = self.get_property(dav.CurrentUserPrincipal())
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/objects.py", line 224, in get_property
    foo = self.get_properties([prop], **passthrough)
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/objects.py", line 256, in get_properties
    properties = response.expand_simple_props(props)
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/davclient.py", line 298, in expand_simple_props
    self.find_objects_and_props()
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/davclient.py", line 221, in find_objects_and_props
    responses = self._strip_to_multistatus()
  File "/home/cpc/.local/lib/python3.10/site-packages/caldav/davclient.py", line 157, in _strip_to_multistatus
    if tree.tag == "xml" and tree[0].tag == dav.MultiStatus.tag:
AttributeError: 'NoneType' object has no attribute 'tag'
```

**Comment by pentux-GitHub** [comment]
Passing by on the current master (0.7 dev): the GTG side of this looks
mostly resolved by the core rewrite, so here's an update in case it
helps whoever revisits it.

The first crash — `queue_set_task` receiving a str and calling the old
`task.get_id()` — is gone: `queue_set_task(self, tid)` now takes an id
by contract, and both callers in datastore.py pass `task.id`. So the
`AttributeError: 'str' object has no attribute 'get_id'` shouldn't
happen anymore.

The second traceback is different in nature: it comes from inside the
`caldav` library (`principal()` → `_strip_to_multistatus` →
`NoneType has no attribute 'tag'`), i.e. the server returned something
the client couldn't parse, not a GTG code path. That one is likely
tied to the server/library versions at the time rather than to GTG
itself; worth re-testing with a current `python-caldav`.

I don't have a way to reproduce the server-side condition here, so I
can't confirm the second half is fully gone — but the GTG-side
`get_id` bug that opened this report is no longer in the tree.

**Comment by pentux-GitHub** [comment]
Fixed by #1265 (merged). The crash was `queue_set_task` calling `task.get_id()` on what was already an id. Its signature now takes the id directly (`def queue_set_task(self, tid)`, generic_backend.py) and the datastore passes `task.id` to match — the `AttributeError: 'str' object has no attribute 'get_id'` can no longer occur.

(The second traceback in the report, `NoneType' object has no attribute 'tag'` inside the caldav client's `_strip_to_multistatus`, is a server/response-parsing error in the caldav library, unrelated to GTG.)

Safe to close.
