### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by stef204** [getting-things-gnome/gtg#1097]
gtg-git version `0.6.r442.gdc0eb1a9-1`

```
% gtg --version
GTG (Getting Things GNOME!) 0.6.0
Using python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]
```
gtk4 `4.14.4`

Trace
```
% gtg

(gtg:561138): Gtk-WARNING **: 13:21:42.904: Child name 'active' not found in GtkStack
2024-05-04 13:21:42,913 - ERROR - application:do_activate:157 - Exception during activation
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/GTG/gtk/application.py", line 151, in do_activate
    self.init_shared()
  File "/usr/lib/python3.12/site-packages/GTG/gtk/application.py", line 233, in init_shared
    self.init_plugin_engine()
  File "/usr/lib/python3.12/site-packages/GTG/gtk/application.py", line 259, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/usr/lib/python3.12/site-packages/GTG/core/plugins/engine.py", line 206, in activate_plugins
    plugin.instance.activate(api)
  File "/usr/lib/python3.12/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 60, in activate
    self.preferences_apply()
  File "/usr/lib/python3.12/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 163, in preferences_apply
    self.add_untouched_tag()
  File "/usr/lib/python3.12/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 95, in add_untouched_tag
    requester = self.plugin_api.get_requester()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PluginAPI' object has no attribute 'get_requester'
Gtk-Message: 13:21:43.003: GtkDialog mapped without a transient parent. This is discouraged.
2024-05-04 13:21:57,388 - INFO - errorhandler:handle_response:140 - Going to exit because either of fatal error or user choice
zsh: IOT instruction (core dumped)  gtg
```

**Comment by stef204** [comment]
EDIT: the problem could be with the `data` as when cloning this repo and running the `launch.sh` script,  `gtg` launches fine. 
If I use the script `./scripts/import_tasks_from_local.sh` it crashes again.
Some compatibility issues with older versions of `gtg` perhaps?

**Comment by picsel2** [comment]
The untouched tasks plugin has not been ported to the plugin api changes of v0.7 yet.
I think that plugins are already addressed in #737 

You could try to deactivate the plugin(s) manually by editing `$XDG_CONFIG_HOME/gtg/gtg.conf` as a workaround until then. For instance my `/home/sebastian/.var/app/org.gnome.GTG/config/gtg/gtg.conf` has a section for the plugin states:
```
[plugins]
enabled = dev_console,urgency_color
disabled = export,gamify,hamster,send_email,untouched_tasks
```

**Comment by stef204** [comment]
@picsel2 </br>
disabling `untouched_tasks` via the method you mentioned works and makes `gtg` launch again with no crash.
hopefully, that plugin will get ported, if still needed.
thanks.

**Comment by stef204** [comment]
closing this.
