### ISSUE TITLE
Hamster integration

### ISSUE THREAD

**Issue by sourcedevelopersdotcom** [getting-things-gnome/gtg#1109]
```python-traceback
Traceback (most recent call last):
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/plugins/hamster/hamster.py", line 300, in browser_cb
    self.decide_start_or_stop_activity(task, widget)
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/plugins/hamster/hamster.py", line 314, in decide_start_or_stop_activity
    self.send_task(task)
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/plugins/hamster/hamster.py", line 75, in send_task

**Comment by lennyhans** [comment]
There is already a proposed change that check that exception, but apparently the integration needs some work
- https://github.com/getting-things-gnome/gtg/pull/1121

**Comment by nekohayo** [comment]
Considering this a duplicate of #683 then...
