### ISSUE TITLE
Hamster Plugin Install Traceback + Subsequent Crash-on-Launch

### ISSUE THREAD

**Issue by APCBoston** [getting-things-gnome/gtg#1139]
Edit: After originally posting the crash-on-launch, I remembered that I had seen a traceback when I enabled the Hamster plugin, but had lost that traceback before I'd been able to post it.  Disabling hamster in `gtg.conf` resolved the crash-on-launch, and I was able to reproduce the traceback when I reenabled Hamster.

Possibly relevant: Hamster is installed as a system package; GTG is installed as a Flatpak.

## Traceback enabling Hamster:

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/plugins.py", line 216, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-6.9.3-76060903-generic-x86_64-with-glibc2.33

## Crash on subsequent launch (Hamster still enabled)

"GTG Encountered an internal fatal error and needs to exit"

Details from the dialog:

```**Context:** Activation

python-traceback
None

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-6.9.3-76060903-generic-x86_64-with-glibc2.33
```

App is installed via Flatpak from the Pop!OS "COSMIC App Store" app (which is just providing a GUI to Flathub).  App has launched and run successfully in the past but this now recurs on every launch.  

Launching from the terminal via `flatpak run` gives this additional context:

```
$ flatpak run org.gnome.GTG
Gtk-Message: 10:11:59.754: Failed to load module "appmenu-gtk-module"
Gtk-Message: 10:11:59.887: Failed to load module "canberra-gtk-module"
2024-09-16 10:12:00,050 - WARNING - general_preferences:get_default_editor_font:89 - Using deprecated but still working font way (UnicodeDecodeError('utf-8', b'\x10\x18R\xe2"\\ 10', 3, 4, 'invalid continuation byte'))
2024-09-16 10:12:00,127 - ERROR - application:do_activate:153 - Exception during activation
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by nekohayo** [comment]
Hi there, isn't this a duplicate of #683 ?

**Comment by pentux-GitHub** [comment]
Housekeeping pass: #683, which nekohayo pointed to above, is now closed, and the Hamster plugin has since been fully ported to the new core (#1287). I'd think this can be closed as resolved.
