### ISSUE TITLE
crash on close

### ISSUE THREAD

**Issue by CatBurglerV8** [getting-things-gnome/gtg#160]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/GTG/plugins/bugzilla/notification.py", line 64, in uinit_pynotify
    pynotify.uninit()
NameError: global name 'pynotify' is not defined

**Comment by izidormatusov** [comment]
This was already fixed in the development branch.
