### ISSUE TITLE
Plugin API: Can't insert button to editor

### ISSUE THREAD

**Issue by marcosdsanchez** [getting-things-gnome/gtg#165]
I've just started using gtg yesterday and it worked great.

Today I open the program after doing my regular updates in my archlinux machine and noticed that tasks where not correctly added.

Exception trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py", line 906, in on_add_task
    self.vmanager.open_task(uid, thisisnew=True)
  File "/usr/lib/python3.4/site-packages/GTG/gtk/manager.py", line 180, in open_task
    clipboard=self.clipboard)
  File "/usr/lib/python3.4/site-packages/GTG/gtk/editor/editor.py", line 189, in __init__
    self.pengine.onTaskLoad(self.plugin_api)
  File "/usr/lib/python3.4/site-packages/GTG/core/plugins/engine.py", line 260, in onTaskLoad
    plugin.instance.onTaskOpened(plugin_api)
  File "/usr/lib/python3.4/site-packages/GTG/plugins/send_email/sendEmail.py", line 48, in onTaskOpened
    plugin_api.add_toolbar_item(self.tb_Taskbutton)
  File "/usr/lib/python3.4/site-packages/GTG/core/plugins/api.py", line 169, in add_toolbar_item
    self.__toolbar.insert(widget, -1)
AttributeError: 'NoneType' object has no attribute 'insert'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/GTG/gtk/crashhandler.py", line 122, in _replacement_excepthook
    res = show_error_window(tb, add_apport_button=add_apport_button)
  File "/usr/lib/python3.4/site-packages/GTG/gtk/crashhandler.py", line 219, in show_error_window
    expander = Gtk.expander_new_with_mnemonic(_("_Details"))
  File "/usr/lib/python3.4/site-packages/gi/overrides/__init__.py", line 38, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.4/site-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'expander_new_with_mnemonic'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/GTG/gtk/browser/browser.py", line 906, in on_add_task
    self.vmanager.open_task(uid, thisisnew=True)
  File "/usr/lib/python3.4/site-packages/GTG/gtk/manager.py", line 180, in open_task
    clipboard=self.clipboard)
  File "/usr/lib/python3.4/site-packages/GTG/gtk/editor/editor.py", line 189, in __init__
    self.pengine.onTaskLoad(self.plugin_api)
  File "/usr/lib/python3.4/site-packages/GTG/core/plugins/engine.py", line 260, in onTaskLoad
    plugin.instance.onTaskOpened(plugin_api)
  File "/usr/lib/python3.4/site-packages/GTG/plugins/send_email/sendEmail.py", line 48, in onTaskOpened
    plugin_api.add_toolbar_item(self.tb_Taskbutton)
  File "/usr/lib/python3.4/site-packages/GTG/core/plugins/api.py", line 169, in add_toolbar_item
    self.__toolbar.insert(widget, -1)
AttributeError: 'NoneType' object has no attribute 'insert'
```

**Comment by izidormatusov** [comment]
I think this was caused by UI redesign by @jakubbrindza. We need to fix plugin APIs

As short term solution: you might want to disable plugins

**Comment by marcosdsanchez** [comment]
Disabling plugins worked. Thanks @izidormatusov

**Comment by nekohayo** [comment]
Let's just consider this is going to be nuked as part of #222 eventually.
