### ISSUE TITLE
Getting UnicodeDecodeError when running master

### ISSUE THREAD

**Issue by accesio** [getting-things-gnome/gtg#167]
Hi,

I followed the instructions from the README.md file but then when I go to run gtg.sh, I get the following error:

```
Setting XDG vars to use default dataset.
2015-09-21 11:26:05,896 - WARNING - __init__:__init__:70 - Backend backend_launchpad could not be loaded: No module named 'launchpadlib'
2015-09-21 11:26:05,904 - WARNING - __init__:__init__:70 - Backend backend_mantis could not be loaded: No module named 'suds'
2015-09-21 11:26:05,913 - WARNING - __init__:__init__:70 - Backend backend_evolution could not be loaded: No module named 'evolution'

(gtg:5869): Gtk-WARNING **: Unknown property: GtkSearchEntry.max-width-chars
Traceback (most recent call last):
  File "./GTG/gtg", line 227, in <module>
    main()
  File "./GTG/gtg", line 173, in main
    manager = Manager(req)
  File "/home/jdamon/Downloads/gtg/GTG/gtk/manager.py", line 72, in __init__
    self.__init_plugin_engine()
  File "/home/jdamon/Downloads/gtg/GTG/gtk/manager.py", line 94, in __init_plugin_engine
    self.pengine = PluginEngine()
  File "/home/jdamon/Downloads/gtg/GTG/core/plugins/engine.py", line 172, in __init__
    info.read(info_file)
  File "/usr/lib/python3.4/configparser.py", line 672, in read
    self._read(fp, filename)
  File "/usr/lib/python3.4/configparser.py", line 993, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 465: ordinal not in range(128)
```

I have the original python-liblarch installed ( not the python3-liblarch ) but I am not sure that this has anything to do with it.

I'm running this on Ubuntu 14.04.

**Comment by izidormatusov** [comment]
Hey, can you provide the content of `~/.config/gtg/gtg.conf`?

**Comment by nekohayo** [comment]
Closing as no info was provided.
