### ISSUE TITLE
broken in gnome 3.18

### ISSUE THREAD

**Issue by tomdurrant** [getting-things-gnome/gtg#172]
After updating to gnome 3.18, gtg is broken. Running from the command lines yeilds:

Traceback (most recent call last):
  File "./GTG/gtg", line 227, in <module>
    main()
  File "./GTG/gtg", line 173, in main
    manager = Manager(req)
  File "/home/tdurrant/git/gtg/GTG/gtk/manager.py", line 70, in __init__
    self.browser = TaskBrowser(self.req, self)
  File "/home/tdurrant/git/gtg/GTG/gtk/browser/browser.py", line 97, in __init__
    self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
GLib.Error: gtk-builder-error-quark: /home/tdurrant/git/gtg/GTG/gtk/browser/taskbrowser.ui:29:1 Can't use <style> here (4)

**Comment by fturco** [comment]
I think I have the same problem. I have just updated to GNOME 3.18 on my Parabola GNU/Linux-libre system. GTG is version r5170.a795d66-1 from Git. I'm using a clean profile, so this is not a configuration problem. Error message:

```
$ gtg
sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: NetworkManager was imported without specifying a version first. Use gi.require_version('NetworkManager', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: NMClient was imported without specifying a version first. Use gi.require_version('NMClient', '1.0') before import to ensure that the right version gets loaded.
2015-10-12 20:17:09,820 - WARNING - __init__:__init__:70 - Backend backend_launchpad could not be loaded: No module named 'launchpadlib'
2015-10-12 20:17:09,822 - WARNING - __init__:__init__:70 - Backend backend_rtm could not be loaded: No module named 'dateutil'
2015-10-12 20:17:09,824 - WARNING - __init__:__init__:70 - Backend backend_evolution could not be loaded: No module named 'dateutil'
2015-10-12 20:17:09,826 - WARNING - __init__:__init__:70 - Backend backend_mantis could not be loaded: No module named 'suds'
Traceback (most recent call last):
  File "/usr/bin/gtg", line 227, in <module>
    main()
  File "/usr/bin/gtg", line 173, in main
    manager = Manager(req)
  File "/usr/lib/python3.5/site-packages/GTG/gtk/manager.py", line 70, in __init__
    self.browser = TaskBrowser(self.req, self)
  File "/usr/lib/python3.5/site-packages/GTG/gtk/browser/browser.py", line 97, in __init__
    self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
GLib.Error: gtk-builder-error-quark: /usr/lib/python3.5/site-packages/GTG/gtk/browser/taskbrowser.ui:29:1 Can't use <style> here (4)
```

**Comment by chron-isch** [comment]
Same here
I tried with versions r5170.a795d66 and r5152.fc8afad

```
% gtg
sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: NetworkManager was imported without specifying a version first. Use gi.require_version('NetworkManager', '1.0') before import to ensure that the right version gets loaded.
sys:1: PyGIWarning: NMClient was imported without specifying a version first. Use gi.require_version('NMClient', '1.0') before import to ensure that the right version gets loaded.
2015-10-13 12:31:42,884 - WARNING - __init__:__init__:70 - Backend backend_evolution could not be loaded: No module named 'evolution'
2015-10-13 12:31:42,888 - WARNING - __init__:__init__:70 - Backend backend_launchpad could not be loaded: No module named 'launchpadlib'
2015-10-13 12:31:42,890 - WARNING - __init__:__init__:70 - Backend backend_mantis could not be loaded: No module named 'suds'
Traceback (most recent call last):
  File "/usr/sbin/gtg", line 227, in <module>
    main()
  File "/usr/sbin/gtg", line 173, in main
    manager = Manager(req)
  File "/usr/lib/python3.5/site-packages/GTG/gtk/manager.py", line 70, in __init__
    self.browser = TaskBrowser(self.req, self)
  File "/usr/lib/python3.5/site-packages/GTG/gtk/browser/browser.py", line 98, in __init__
    self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
GLib.Error: gtk-builder-error-quark: /usr/lib/python3.5/site-packages/GTG/gtk/browser/taskbrowser.ui:29:1 Can't use <style> here (4)```

**Comment by marcosdsanchez** [comment]
```
➜  ~  gtg
sys:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/bin/gtg", line 56, in <module>
    from GTG import info
ImportError: No module named 'GTG'
```
