### ISSUE TITLE
 gtg 0.3.1-1 (Ubuntu 14.04.3) crashes every time when i click on any tag right after start

### ISSUE THREAD

**Issue by igloo777** [getting-things-gnome/gtg#174]
Hi, gtg crashes every time when i click on any tag right after start. 
Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 1184, in on_select_tag
    self.apply_filter_on_panes(tagname)
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 1161, in apply_filter_on_panes
    vtree.apply_filter(filter_name, refresh=refresh)
  File "/usr/lib/python2.7/dist-packages/liblarch/viewtree.py", line 276, in apply_filter
    self.__ft.apply_filter(filter_name, parameters, reset, refresh)
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 634, in apply_filter
    self.refilter()
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 312, in refilter
    self.send_remove_tree(node_id, self.root_id)
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 286, in send_remove_tree
    self.callback('deleted', node_id, path)
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 124, in callback
    func(node_id,path)
  File "/usr/lib/python2.7/dist-packages/liblarch/viewtree.py", line 115, in __emit
    func(node_id,path)
  File "/usr/lib/python2.7/dist-packages/liblarch_gtk/treemodel.py", line 161, in remove_task
    raise Exception("Trying to remove node %s with no iterator"%node_id)
Exception: Trying to remove node 8a4a082c-7e67-4acf-ae76-8a826276f2a8 with no iterator

**Comment by sagarghuge** [comment]
@igloo777  Thanks for reporting, But I am not able to reproduce issue with latest version of GTG. 
I am running it using source code on Ubuntu 15.10. 
I directly clicked on Tags on left sidebar. 

Can you specify steps to reproduce same issue.

**Comment by jakubbrindza** [comment]
@igloo777 this cannot be reproduced on Fedora 22 either, no crash observed.

Try to give more specification into what structure your tasks are maybe? I'm wondering what could make a node cause to have no iterator and thus cause the exception.
