### ISSUE TITLE
gi._glib.GError: <object> requires attribute "id" in preferences.ui

### ISSUE THREAD

**Issue by LionelR** [getting-things-gnome/gtg#176]
Get an error when calling ./gtg.sh in the Git cloned repo, on Ubuntu 14.04 

``` bash
Setting XDG vars to use default dataset.
2015-11-17 09:00:32,582 - WARNING - __init__:__init__:70 - Backend backend_mantis could not be loaded: No module named 'suds'
2015-11-17 09:00:32,583 - WARNING - __init__:__init__:70 - Backend backend_launchpad could not be loaded: No module named 'launchpadlib'
2015-11-17 09:00:32,584 - WARNING - __init__:__init__:70 - Backend backend_evolution could not be loaded: No module named 'evolution'

(gtg:1337): Gtk-WARNING **: Unknown property: GtkSearchEntry.max-width-chars

(gtg:1337): Gtk-WARNING **: Unknown property: GtkHeaderBar.decoration-layout
Traceback (most recent call last):
  File "./GTG/gtg", line 227, in <module>
    main()
  File "./GTG/gtg", line 173, in main
    manager = Manager(req)
  File "/home/lionel/gtg/gtg/GTG/gtk/manager.py", line 82, in __init__
    self.preferences = Preferences(self.req, self)
  File "/home/lionel/gtg/gtg/GTG/gtk/preferences.py", line 39, in __init__
    builder.add_from_file(self.PREFERENCES_UI_FILE)
gi._glib.GError: /home/lionel/gtg/gtg/GTG/gtk/ui/preferences.ui:24:1 <object> requires attribute "id"
```

**Comment by nekohayo** [comment]
Hi there, does this still happen with the current state of the git version?

**Comment by diegogangl** [comment]
Never seen this in master
