### ISSUE TITLE
Crash when opening preferences

### ISSUE THREAD

**Issue by javaworms** [getting-things-gnome/gtg#199]
GTG crashes when I try to open preferences. I am using Kubuntu 16.04. Here is the traceback:

Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 416, in open_preferences
    self.vmanager.open_preferences(self.config)
  File "/usr/share/gtg/GTG/gtk/manager.py", line 239, in open_preferences
    self.preferences.activate()
  File "/usr/share/gtg/GTG/gtk/preferences.py", line 144, in activate
    self._refresh_preferences_store()
  File "/usr/share/gtg/GTG/gtk/preferences.py", line 129, in _refresh_preferences_store
    self.shortcut.refresh_accel()
  File "/usr/share/gtg/GTG/gtk/preferences.py", line 214, in refresh_accel
    self.new_task_binding = get_saved_binding()
  File "/usr/share/gtg/GTG/tools/shortcut.py", line 50, in get_saved_binding
    list_keys = call_subprocess(CHECK_VERSION).splitlines()
  File "/usr/share/gtg/GTG/tools/shortcut.py", line 160, in call_subprocess
    out = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by sagarghuge** [comment]
I am using 0.3.2, it's working fine at my end. Can you please check your gtg version ?

**Comment by nekohayo** [comment]
Reopen if you can reproduce with git everything.

**Comment by khangly** [comment]
I had the same problem to. Look at this [link](https://stackoverflow.com/questions/9935151/popen-error-errno-2-no-such-file-or-directory), all you need to do is go to line 160 of the file `/usr/share/gtg/GTG/tools/shortcut.py` and change it to:
```python
    out = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
```

**Comment by nekohayo** [comment]
@khangly that shortcut.py file doesn't exist in GTG 0.4 or the git version. Please check if you can encounter this issue with the git version's code as-is, because I've never encountered it either.

**Comment by khangly** [comment]
> @khangly that shortcut.py file doesn't exist in GTG 0.4 or the git version. Please check if you can encounter this issue with the git version's code as-is, because I've never encountered it either.

I'm using version 0.3.1 from Debian Buster repo, it works well when I did the change above so I see no need to update to version 0.4. I think OP is using an even older version so I guess this doesn't happen in newer versions?
