### ISSUE TITLE
RTM Auth: GTG (python-3) never gets the token ?

### ISSUE THREAD

**Issue by khurshid-alam** [getting-things-gnome/gtg#201]
1. It opens the browser window and authenticates with rtm properly. 

2. But after that nothing happens. Browser window doesn't close. Synchronization window doesn't close. It keeps spinning but never seems to get the required token.

3. After restart it automatically opens the rtm authentication page in the browser. But nothings happens after.

From the log:

```
Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 1327, in on_backend_needing_interaction
    infobar.set_interaction_request(description, interaction_type,
AttributeError: 'NoneType' object has no attribute 'set_interaction_request'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/crashhandler.py", line 122, in _replacement_excepthook
    res = show_error_window(tb, add_apport_button=add_apport_button)
  File "/usr/share/gtg/GTG/gtk/crashhandler.py", line 219, in show_error_window
    expander = Gtk.expander_new_with_mnemonic(_("_Details"))
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'expander_new_with_mnemonic'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 1327, in on_backend_needing_interaction
    infobar.set_interaction_request(description, interaction_type,
AttributeError: 'NoneType' object has no attribute 'set_interaction_request'
Using PPAPI flash.
Created new window in existing browser session.
```

**Comment by khurshid-alam** [comment]
@izidormatusov ?

**Comment by khurshid-alam** [comment]
I think infobar section to confirm after getting token gets broken. Last known good commit (for py3, gtk3) for which it was working was: 3bea2ca60bb4f2e55eb6d4652afa0fef1006b3d0

**Comment by nekohayo** [comment]
I'm working on putting this project back on its feet with the goal of getting a release out of the door.

This issue here is up for grabs for anyone wanting to see it happen. Please test with the development version, and contribute code (or bring in someone who can) to the project to bring this plugin back into good shape, or it risks getting decommissioned as part of issue #222.

**Comment by pentux-GitHub** [comment]
Housekeeping while reviewing dormant issues for 0.7. The RTM backend was decommissioned as anticipated in this thread: it now lives in GTG/backends/unmaintained/ and BackendFactory only scans the top-level backends directory, so this code is never loaded. This report describes a bug in code that no longer runs; a future RTM revival would be a rewrite against the new core anyway. I'd think it's safe to close as obsolete.

**Comment by pentux-GitHub** [comment]
Housekeeping: the RTM backend now lives in `backends/unmaintained/`, is not loaded and not shipped, so this can no longer occur nor be fixed — it seems safe to close.
