### ISSUE TITLE
Fedora 25: AttributeError: 'NoneType' object has no attribute 'get_submenu'..

### ISSUE THREAD

**Issue by sudo-justinwilson** [getting-things-gnome/gtg#205]
When I tick plugins, the whole program crashes with the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/GTG/gtk/plugins.py", line 254, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/usr/lib/python2.7/site-packages/GTG/core/plugins/engine.py", line 221, in activate_plugins
    plugin.instance.activate(api)
  File "/usr/lib/python2.7/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 74, in activate
    self.plugin_api.add_menu_item(self.menu_item)
  File "/usr/lib/python2.7/site-packages/GTG/core/plugins/api.py", line 135, in add_menu_item
    widget.get_submenu().append(item)
AttributeError: 'NoneType' object has no attribute 'get_submenu'
```
uname: Linux fedora25.local 4.9.10-200.fc25.x86_64 #1 SMP Wed Feb 15 23:28:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nekohayo** [comment]
Was that the git version, or 0.3.1? Anyhow, GTG got dropped from Fedora, in the meantime you can use the flatpak package of 0.3.1 here: https://github.com/bilelmoussaoui/gtg-flatpak

**Comment by diegogangl** [comment]
Fixed in Master
