### ISSUE TITLE
Tracebacks while typing tags in the task editor

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#259]
This is what I get for every character that gets typed after a "@" in the task editor:

```
Traceback (most recent call last):
  File "/home/jeff/gtg/GTG/gtk/editor/taskview.py", line 550, in modified
    self._detect_tag(buff, local_start, local_end)
  File "/home/jeff/gtg/GTG/gtk/editor/taskview.py", line 740, in _detect_tag
    self.add_tag_callback(my_word)
  File "/home/jeff/gtg/GTG/core/task.py", line 707, in add_tag
    cgi.escape(tagname), sep, c)
AttributeError: module 'cgi' has no attribute 'escape'
```

**Comment by nekohayo** [comment]
...It also creates a tag for each character being typed (personally unless it can be made bulletproof, I think we should NOT live-create tags while they are being typed, it should wait for validation somehow, maybe after a timeout)
