### ISSUE TITLE
Traceback when clicking the "Synchronization" menu

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#284]
This is what happens when you click "Synchronization" in the menubutton:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_BackendsDialog_delete_event not found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_close_button_clicked not found
```

Nonetheless, a window appears... showing only the "local file" backend. If then you click the "+" button to try to add another (synchronization/online) backend, you get this second traceback:

```
Traceback (most recent call last):
  File "/home/jeff/gtg/GTG/gtk/backends/__init__.py", line 228, in on_add_button
    self.add_panel.refresh_backends()
  File "/home/jeff/gtg/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/home/jeff/gtg/GTG/gtk/backends/backendscombo.py", line 72, in refresh
    ordered_backend_types = sorted(
  File "/home/jeff/gtg/GTG/gtk/backends/backendscombo.py", line 74, in <lambda>
    key=lambda btype: btype[1].Backend.get_human_default_name())
AttributeError: module 'GTG.backends.backend_signals' has no attribute 'Backend'
```

The big question is whether the online backends will reappear someday... but I guess for now we can simply 1) remove/comment-out that menu entry so that users can't trigger such tracebacks 2) document the need for those backends to be resurrected and this bug to be fixed? But where to document that, in a code comment, in a readme file, in a ticket, ?

**Comment by diegogangl** [comment]
I fixed the signals. I think it's useful to entice potential developers. Maybe we could have an issue or something in the wiki?
