### ISSUE TITLE
Can't open Sync menu on Ubuntu 20.04

### ISSUE THREAD

**Issue by XioNoX** [getting-things-gnome/gtg#295]
Today's master fails with the following error:
```
Traceback (most recent call last):
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/application.py", line 269, in open_backends_manager
    self.open_edit_backends()
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/application.py", line 353, in open_edit_backends
    self.backends_dialog = BackendsDialog(self.req)
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/__init__.py", line 72, in __init__
    self._create_widgets_for_treeview()
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/__init__.py", line 193, in _create_widgets_for_treeview
    self.backends_tv = BackendsTree(self)
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/backendstree.py", line 50, in __init__
    self.refresh()
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/backendstree.py", line 66, in refresh
    self.add_backend(backend)
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/backendstree.py", line 97, in add_backend
    self.dialog.get_pixbuf_from_icon_name(backend.get_name(),
  File "/home/xionox/Documents/Projects/github/gtg/gtg/env/lib/python3.8/site-packages/GTG/gtk/backends/__init__.py", line 118, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'backend_localfile' not present in theme Yaru (0)
```

**Comment by nekohayo** [comment]
Strangely enough, I get a totally different error than yours, when I go into "Synchronization" and click the "+" button to add a backend (is that what you did?):

```
Traceback (most recent call last):
  File "/home/jeff/gtg/GTG/gtk/backends/__init__.py", line 228, in on_add_button
    self.add_panel.refresh_backends()
  File "/home/jeff/gtg/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/home/jeff/gtg/GTG/gtk/backends/backendscombo.py", line 72, in refresh
    ordered_backend_types = sorted(
  File "/home/jeff/gtg/GTG/gtk/backends/backendscombo.py", line 74, in <lambda>
    key=lambda btype: btype[1].Backend.get_human_default_name())
AttributeError: module 'GTG.backends.backend_signals' has no attribute 'Backend'
```

I don't know why I'm not getting your error at all.

I thought @diegogangl had disabled the dialog entirely in commit 7fcf2aa00e but apparently not. If all the backends other than the local file backend are deactivated (?), for the 0.4 release I'd suggest making the "Synchronization" menu item "insensitive" (or auto-hidden when there are no viable backend plugins enabled) so that people can't run into this problem; if people want to resurrect the non-local backends they can then contribute code in that specialized area...

**Comment by XioNoX** [comment]
Not even trying to click "+", the error is when I try to click on "Synchronization" in the drop down.

**Comment by diegogangl** [comment]
Looks like a theme issue with Ubuntu's Yaru. @nekohayo I don't get your error at all, and it should be fixed by that commit. I do agree about disabling it, it needs a re-design too and a lot of work.

**Comment by nekohayo** [comment]
My test machine is also running the Yaru theme (both GTK and icons), so I don't understand why I'm not running into the same issues as @XioNoX ... oh well, it is a mystery.
