### ISSUE TITLE
Clarify more dependencies needed to run the git version on Ubuntu and Debian

### ISSUE THREAD

**Issue by iootaa** [getting-things-gnome/gtg#303]
Hello there,

I've decided to contribute by testing the version from git (until now I've being using intensively the Debian package, version 0.3.1). My operating system is Tails (https://tails.boum.org), based on debian Buster

I followed the instructions from README.md : 

```
$ git clone https://github.com/getting-things-gnome/gtg.git
$ cd gtg
# apt install python3-pip
# apt install python3-nose python3-xdg python3-pyflakes python3-pep8 python3-pycodestyle python3-mock python3-dbus gobject-introspection 
```
Runs smoothly
Unfortunatelly, this last step brings the following errors : 

**$ torify pip3 install -r requirements.txt**

```
Requirement already satisfied: nose in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.3.7)
Collecting spec (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/fa/73/efc20b115cb391e89c9e4902a56ba5d0e244feb306e567383ab9b8ff72ab/spec-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.25)
Requirement already satisfied: pyflakes in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.0.0)
Requirement already satisfied: pep8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: pycodestyle in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (2.4.0)
Requirement already satisfied: mock in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.0.0)
Obtaining liblarch from git+http://github.com/getting-things-gnome/liblarch.git#egg=liblarch (from -r requirements.txt (line 8))
  Updating ./src/liblarch clone
Collecting dbus-python (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/62/7e/d4fb56a1695fa65da0c8d3071855fa5408447b913c58c01933c2f81a269a/dbus-python-1.2.16.tar.gz (576kB)
    100% |████████████████████████████████| 583kB 124kB/s 
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (3.30.4)
Requirement already satisfied: six<2.0 in /usr/lib/python3/dist-packages (from spec->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject->-r requirements.txt (line 10)) (1.16.2)
Building wheels for collected packages: dbus-python
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-97usu3z4 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: spec, liblarch, dbus-python
  The script spec is installed in '/home/amnesia/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for liblarch
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kzt63hfs/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    creating /tmp/pip-install-vccypz6s/dbus-python/build
    creating /tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
[...] 
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================
    
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vccypz6s/dbus-python/setup.py", line 111, in <module>
        tests_require=['tap.py'],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vccypz6s/dbus-python/setup.py", line 64, in run
        cwd=builddir)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-vccypz6s/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kzt63hfs/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-vccypz6s/dbus-python/

```

It does not prevent GTG form starting, but I stumbled upon other bugs and I would like to start on good bases.

Do you have any hint?

BTW, I'm really glad to see this project revival!
Thank you, cheers

**Comment by diegogangl** [comment]
Sounds like it's missing python's libraries, does `apt install python3-dev` help?
Thanks for testing!

**Comment by iootaa** [comment]
Hi diegogangl, and thanks for your answer!

I did `apt install python3-dev` and I still get a similar error message. **The installation was successfull** after also running `apt install pkg-config libdbus-glib-1-dev libgirepository1.0-dev`

Should we update the documentation accordingly?
Thanks for your help, cheers

**Comment by diegogangl** [comment]
Interesting, yeah we might have to add it. Assigning to @nekohayo since that's his turf

**Comment by nekohayo** [comment]
This is a similar problem to what was seen in https://github.com/getting-things-gnome/gtg/issues/242#issuecomment-619821939 ; I have some minor local changes to the README.md on my end for this, but I ended up not committing them because I wasn't really sure what I was looking at anymore. Even with my Ubuntu GTG test machine for this specific purpose, it ends up being pretty confusing.

It's also strange that pip wouldn't catch those issues / recommend what to do?

@iootaa were all three of your last dependencies (pkg-config libdbus-glib-1-dev libgirepository1.0-dev) strictly necessary for it to work, i.e. if you haven't already you could check by installing them one at a time? Otherwise I guess I could just write them all as-is in the README but I prefer to keep it relatively simple if possible :)

**Comment by reubenbrown13** [comment]
the readme still doesn't show python-liblarch as an ubuntu dependency.

**Comment by leio** [comment]
I took a stab at some README dependency updates in #391. As I'm not a debian/ubuntu/fedora user, I'm not sure if something isn't missing; logically it shouldn't, but I'm not familiar enough with what could be left out from indirect deps in those distros

**Comment by iootaa** [comment]
Hi there,

I ran through the installation process again on a fresh Debian 10, and more dependencies are required than documented:

`apt install python3-venv python3-pip` is needed before to install liblarch with pip3

Then, starting `./launch.sh` reads `"Command "python setup.py egg_info" failed with error code 1 in /home/amnesia/Persistent/gtg/src/liblarch/`.  Running `apt install python3-setuptools` solves this

Last thing, the Export plugin requires `pdfjam` which is part of `texlive-extra-utils` in Debian 10

I've been glad to give a try to this git version, thank you all for your great work!
