### ISSUE TITLE
Meson tracebacks when running a translation with duplicate entries

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#343]
So, not entirely sure if it's a proper bug or not, but just in case it interests @leio ... I've been cleaning up translatable strings and unifying them in the code/.ui files/etc. (including removing some from `GTG/gtk/browser/__init__.py`), and it ended up in a situation where my po/fr.po had these two occurrences:

```
#: GTG/gtk/data/context_menus.ui:41
msgid "Mark as Done"
msgstr "Marquer comme fait"
```

```
#: GTG/gtk/data/task_editor.ui:373 GTG/gtk/browser/__init__.py:37
msgid "Mark as Done"
msgstr "Marquer comme fait"
```

However, meson doesn't like that, when you launch gtg.sh:

```
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gtg'
dev/gtg/po/fr.po:566: duplicate message definition...
dev/gtg/po/fr.po:134: ...this is the location of the first definition
msgfmt: found 1 fatal error
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.54.2', 'console_scripts', 'meson')()
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 228, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 217, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 165, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/gettext.py", line 118, in run
    if gen_gmo(src_sub, bld_sub, langs) != 0:
  File "/usr/lib/python3.8/site-packages/mesonbuild/scripts/gettext.py", line 65, in gen_gmo
    subprocess.check_call(['msgfmt', os.path.join(src_sub, l + '.po'),
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', 'dev/gtg/po/fr.po', '-o', 'dev/gtg/.local_build/po/fr.gmo']' returned non-zero exit status 1.
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by leio** [comment]
They ought to be getting merged into one as

```
#: GTG/gtk/data/context_menus.ui:41 GTG/gtk/data/task_editor.ui:373 GTG/gtk/browser/__init__.py:37
msgid "Mark as Done"
msgstr "Marquer comme fait"
```

or something like that with the ninja gtg-update-po run; did it not or you were touching the po files manually?

**Comment by nekohayo** [comment]
Hmm I guess my question was rather if meson should catch the traceback and provide a cleaner error (or warning) message, but then I realize now that this has nothing to do with GTG itself and is maybe something I should file in Meson itself, but seeing how that project is already overflowing with bug reports and reporting for what is essentially a user error is complicated, I think I'll just close this ticket here and forget about it :)
