### ISSUE TITLE
New Taskview ends in failed test 

### ISSUE THREAD

**Issue by oyren** [getting-things-gnome/gtg#488]
I haven't really done any digging yet due to time constraints, but when I run the test I get the following:
```
running install tests
/build/source/GTG/gtk/editor/taskview.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GLib, Gdk, GObject

(run-tests:324): Gdk-CRITICAL **: 18:50:55.421: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
...........................................................E.........................................
======================================================================
ERROR: Failure: TypeError (constructor returned NULL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/9fm50f5q5qvpq10ja0jxk1bamv1grhhy-python3.8-nose-1.3.7/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/nix/store/9fm50f5q5qvpq10ja0jxk1bamv1grhhy-python3.8-nose-1.3.7/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/nix/store/9fm50f5q5qvpq10ja0jxk1bamv1grhhy-python3.8-nose-1.3.7/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/nix/store/9fm50f5q5qvpq10ja0jxk1bamv1grhhy-python3.8-nose-1.3.7/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/nix/store/346skv0d24rqnf4npknbp9h5bs14j8zy-python3-3.8.6/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/build/source/tests/core/test_taskview.py", line 21, in <module>
    from GTG.gtk.editor.taskview import TaskView, TAG_REGEX
  File "/build/source/GTG/gtk/editor/taskview.py", line 53, in <module>
    class TaskView(Gtk.TextView):
  File "/build/source/GTG/gtk/editor/taskview.py", line 128, in TaskView
    CURSOR_HAND = Gdk.Cursor.new(Gdk.CursorType.HAND2)
TypeError: constructor returned NULL

----------------------------------------------------------------------
Ran 101 tests in 0.140s

FAILED (errors=1)
````

**Comment by diegogangl** [comment]
I can't replicate this, which GTK version are you running?

**Comment by oyren** [comment]
I'm not sure because I can't find a way to check it, but it should be GTK 3.24.21.
If I don't run the tests, everything seems to work.

**Comment by diegogangl** [comment]
> (run-tests:324): Gdk-CRITICAL **: 18:50:55.421: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

Makes sense, looks like GDK is failing because it can't get a display. Are you running this on Wayland?

What happens if you set the display enviroment variable?

```
$ DISPLAY="localhost:0"

$ export DISPLAY
```

[(Taken from here)](https://www.ibm.com/support/pages/display-environment-variable-must-be-set-or-alarming-failure-occurs)

**Comment by oyren** [comment]
Thanks was a packing error. 
https://github.com/NixOS/nixpkgs/pull/101399
