### ISSUE TITLE
Child task gets removed when closing their editor while the parent task editor is open

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#496]
1. Have a task with a child (using the default tasks or create custom ones)
2. Open the child task editor
3. Open the parent task editor
4. Close the child task editor
5. See how the child task disappears and gets lost

Here's an (a bit more convoluted) example:
![Animation](https://user-images.githubusercontent.com/1196130/97096202-c73cea00-1668-11eb-8497-a7139dc8aee7.gif)

Exception while trying to click on the child task in the open parent task editor:
```
2020-10-25 02:22:28,806 - ERROR - application:open_task:483 - Task 2376f725-ab76-4de9-b97a-489bf9bfb3d2 could not be found!
Traceback (most recent call last):
  File "GTG/gtk/editor/text_tags.py", line 132, in on_tag
    view.open_subtask_cb(self.tid)
  File "GTG/gtk/editor/editor.py", line 709, in open_subtask
    self.app.close_task(task.parents[0])
AttributeError: 'NoneType' object has no attribute 'parents'
```

I am on commit 02402912 (upstream master)

**Comment by Neui** [comment]
Possible the same root bug:
1. Open the task editor
2. Click the "Open parent task" button

This will delete the task and its children on the task whose button you clicked on it.
