### ISSUE TITLE
With the new emojis-based code, crash when opening the tag properties editing dialog for a tag with legacy pixmap icon name

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#541]
This is what happens when I try to edit an old icon-laden tag to choose an emoji:

```
2021-01-19 09:50:08,059 - DEBUG - application:do_activate:125 - Application activation finished
2021-01-19 09:53:14,829 - DEBUG - main_window:on_task_treeview_button_press_event:913 - Received button event #1 at 143.98538208007812,420.2091064453125
2021-01-19 09:53:17,189 - DEBUG - main_window:on_tag_treeview_button_press_event:827 - Received button event #1 at 78, 457
2021-01-19 09:53:19,025 - DEBUG - main_window:on_tag_treeview_button_press_event:827 - Received button event #3 at 79, 453
Traceback (most recent call last):
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/simple_color_selector.py", line 108, in on_expose
    self.__draw(cr)
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/simple_color_selector.py", line 71, in __draw
    Gdk.cairo_set_source_color(gdkcontext, my_color)
TypeError: Argument 1 does not allow None as a value
Traceback (most recent call last):
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/simple_color_selector.py", line 108, in on_expose
    self.__draw(cr)
  File "/home/user/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/simple_color_selector.py", line 71, in __draw
    Gdk.cairo_set_source_color(gdkcontext, my_color)
TypeError: Argument 1 does not allow None as a value

(gtg:10017): Gtk-WARNING **: 09:53:22.450: drawing failure for widget 'GTG+gtk+browser+simple_color_selector+SimpleColorSelectorPaletteItem': NULL pointer

(gtg:10017): Gtk-WARNING **: 09:53:22.450: drawing failure for widget 'GtkBox': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.450: drawing failure for widget 'GtkBox': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GtkAlignment': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GTG+gtk+browser+simple_color_selector+SimpleColorSelector': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GtkAlignment': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GtkBox': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GtkBox': NULL pointer
(gtg:10017): Gtk-WARNING **: 09:53:22.451: drawing failure for widget 'GTG+gtk+browser+tag_editor+TagEditor': NULL pointer
python3: ../../../../src/cairo.c:524: cairo_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)' failed.
Aborted (core dumped)
```

**Comment by diegogangl** [comment]
Can't reproduce this, even with your dataset. It doesn't make much sense either :thinking: 
Which tag is giving you this crash?

**Comment by nekohayo** [comment]
Seems to happen any time with any of the tags on an Ubuntu 20.04 testing machine with a slow hard drive...

**Comment by Neui** [comment]
The error is the same as the one posted in #411

**Comment by nekohayo** [comment]
Turns out that the deprecated method really was the cause for this, and @diegogangl has a fix pending in a branch, which I have tested and can confirm it fixes this.
