### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by asakura42** [getting-things-gnome/gtg#559]
Build failure when installing `gtg-git` package from Arch Linux User repo. Looks like build starts ok, but later error appears:

```
ERROR: Failure: AttributeError ('gi.repository.Gtk' object has no attribute 'Container')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.9/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.9/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/asakura/.cache/yay/gtg-git/src/gtg/tests/core/test_quickadd.py", line 21, in <module>
    from GTG.gtk.browser.quick_add import parse
  File "/home/asakura/.cache/yay/gtg-git/src/gtg/GTG/gtk/browser/quick_add.py", line 27, in <module>
    from GTG.gtk.editor.taskview import TAG_REGEX
  File "/home/asakura/.cache/yay/gtg-git/src/gtg/GTG/gtk/editor/taskview.py", line 28, in <module>
    from gi.repository import Gtk, GLib, Gdk, GObject
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'

FAILED (errors=2)
==> ERROR: A failure occurred in check().
```

So `check()` just runs `python run-tests`

**Comment by Neui** [comment]
Looks like it uses GTK 4 which dropped some stuff (including the used `Gtk.Container`), while GTG currently still uses GTK 3.
So probably it can be fixed specifying the versions in the tests like what we do in the program entry:
```python
gi.require_version('Gdk', '3.0')
gi.require_version('Gtk', '3.0')
```

**Comment by asakura42** [comment]
> Looks like it uses GTK 4 which dropped some stuff (including the used `Gtk.Container`), while GTG currently still uses (and expects) GTK 3.
> So probably it can be fixed specifying the versions in the tests like what we do in the program entry:
> 
> ```python
> gi.require_version('Gdk', '3.0')
> gi.require_version('Gtk', '3.0')
> ```

And where should I put these lines?

**Comment by asakura42** [comment]
I put

```
import gi
gi.require_version('Gdk', '3.0')
gi.require_version('Gtk', '3.0')
```

after `import nose` in `run-tests` and all looks like works ok. Now I'll try build it.

**Comment by asakura42** [comment]
It works now.

**Comment by diegogangl** [comment]
Thanks @asakura42 and @Neui!
