### ISSUE TITLE
No data after new_file_format

### ISSUE THREAD

**Issue by morhe-blip** [getting-things-gnome/gtg#565]
Hello,

after my last git pull --rebase (which installed the new_file_format) all data (tasks and tags) are empty.

If I create new task, close GTG and re-open it, the new task is also not present.
The original data in the /tmp folder is untouched.

How to reproduce is easy:
run GTG via ./launch.sh and this is it.

Debug information does not throw any warning or errors (at least none I can see).

Is there any additional information you need?
I am new to GitHub so I am not familiar with the procedures.

**Comment by WhilelM** [comment]
Same problem here.

**Comment by diegogangl** [comment]
Hey, thanks for reporting. Can you check if this is fixed for you now?

**Comment by morhe-blip** [comment]
Hi,

sorry, it is still not fixed.
Still no tags/tasks at startup; creating some tasks, closing and re-opening GTG makes the list empty again.
I don't see any changes in any files. To me it looks as if there is no output from the program into a file.
However, I do not get any warnings, so this is just my opinion.

Is there anything I can try to help (maybe some output of the dev console, if you tell me what to try)?

**Comment by diegogangl** [comment]
that's really weird, can you show me your directory structure in tmp/default?

**Comment by morhe-blip** [comment]
~/tmp/default/xdg/cache
folders within: 
gstreamer-1.0
mesa_shader_cache
mozilla
yelp
event-sound-cache.tdb.5088b94f93964cf3815ce9a476403bfc.x86_64-pc-linux-gnu

~/tmp/default/xdg/config
folders:
gtg --> plugins, backends.conf, gtg.conf, tasks.conf
yelp --> empty

~/tmp/default/xdg/data
folders:
gtg --> backup, gtg_tasks.xml, projects.xml, tags.xml
webkitgtk

Is that enough information?

**Comment by morhe-blip** [comment]
I also read in the specs of the new file format, that all data is (or should be) stored in one file gtg_data.xml.
This file is not present and is not created in the /tmp directory. This is strange imho because even if the old gtg_tasks.xml is (for whatever reason) unused, a new file should be created.
But DEBUG does not throw any warning about permission problems (which would be strange as well, because it always worked in the past).
Maybe something in the Python code?

**Comment by morhe-blip** [comment]
I tried some new things to get a better idea of what's happening:

1. I deleted the entire tmp folder and ran the new version. Then everything is fine, it starts with an empty tasklist (as expected) and creates a new gtg_data.xml which then keeps tasks that I create within GTG.
2. Importing the data from the Flatpak version changes nothing, the newly created gtg_data.xml is still used.
3. Deleting gtg_data.xml and keeping the imported Flatpak data results in an empty tasklist, so no data is imported.
4. Deleting gtg_data.xml and replacing it with my old gtg_tasks.xml, which I renamed to gtg_data.xml finally throws an error (as it should):

> Traceback (most recent call last):
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 456, in register_backend
    source.initialize(connect_signals=False)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 819, in initialize
    self.backend.initialize()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 134, in initialize
    self.datastore.load_tag_tree(self.tag_tree)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 229, in load_tag_tree
    for element in tag_tree.iter('tag'):
AttributeError: 'NoneType' object has no attribute 'iter'
Traceback (most recent call last):
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'

From my perspective the problem, is that the old gtg_tasks is not translated into the new format. If gtg_data.xml is present, everything is just fine. So the transition with no gtg_data and gtg_tasks not translated seems to be the problem.

**Comment by diegogangl** [comment]
There's something funny about that tmp folder structure, why is there webkit and yelp stuff?
Renaming gtg_tasks.xml to gtg_data.xml is going to break versioning because they are two fairly different file formats.

For some reason gtg isn't finding you gtg_tasks.xml to convert to the new format

**Comment by morhe-blip** [comment]
I don't know, where these folders come from.
However I played around a little bit and I think I can narrow the problem somewhat.

I installed a complete new version of GTG and everything worked.
Inserting the old data files result in an error that is very similar to the one reported by nekohayo https://github.com/getting-things-gnome/gtg/pull/522#issuecomment-762921665 :

> 2021-02-24 19:55:03,759 - WARNING - backend_localfile:initialize:118 - Found old file. Running versioning code.
Traceback (most recent call last):
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 456, in register_backend
    source.initialize(connect_signals=False)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/datastore.py", line 819, in initialize
    self.backend.initialize()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 120, in initialize
    tree = versioning.convert(old_path, self.datastore)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/versioning.py", line 74, in convert
    new_task = convert_task(task, ds)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/versioning.py", line 256, in convert_task
    new_content.text = et.CDATA(convert_content(content.text))
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/core/versioning.py", line 268, in convert_content
    text = html.unescape(content)
  File "/usr/lib/python3.8/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/home/moritz/gtg/.local_build/install/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'


Another similarity is that, the presence of the old backends.conf triggers the bug. So with an empty data folder, if the old backends.conf is present, the task list is empty an will not be saved. If you like I can post my old backends.conf here, but when I was testing I found that the bug only occurs when "default" is set to TRUE.

**Comment by morhe-blip** [comment]
Now the old data is imported. Thanks a lot!

The old backends.conf seems to be the problem; if I delete the tmp folder an copy my old tmp folder, it still does not work. Deleting backends.conf however triggers the correct versioning. I cannot say if this is a problem because I messed around with so much backup copies and deleting/modifying single files that I don't know if this is just some relic from my mess.

If there are no objections this issue can be closed.

Thanks again to Diego!
