### ISSUE TITLE
GTG 0.5 not launching when `]]>` is present in previous task data

### ISSUE THREAD

**Issue by niconil** [getting-things-gnome/gtg#613]
on ubuntu18.04 i've just updated GTG 0.4 to 0.5
but the GTG window does not open !

in a terminal :

```
$ flatpak run org.gnome.GTG -v
GNOME keyring not found, passwords will be not stored after restarting GTG
GTG (Getting Things GNOME!) v0.5
Using python 3.8.8 (default, Nov 10 2011, 15:00:00) 
[GCC 10.2.0]
For more information: https://wiki.gnome.org/Apps/GTG
$
```

but no more !
- how to have more detail of the problem
- what is the meaning of the first line "GNOME keyring ..."
- did i miss something ? a migration procedure ...

**Comment by diegogangl** [comment]
Hi, could you try running it like `flatpak run org.gnome.GTG -d` ?

**Comment by nekohayo** [comment]
@niconil are you running the `-v` parameter for a particular reason? It's not the equivalent of "verbose" (you want `-d` for that), `-v` only prints the version number without launching the app.

**Comment by niconil** [comment]
ok thanks i don't know the debug option

with the -d option i find a nice exception

$ flatpak run org.gnome.GTG -d
GNOME keyring not found, passwords will be not stored after restarting GTG
2021-04-07 08:00:05,465 - DEBUG - application:set_logging:587 - Debug output enabled.
Gtk-Message: 08:00:05.860: Failed to load module "canberra-gtk-module"
2021-04-07 08:00:05,863 - DEBUG - __init__:__init__:60 - Backends found: ['backend_localfile', 'backend_signals']
2021-04-07 08:00:05,965 - WARNING - backend_localfile:this_is_the_first_run:154 - Found old file. Running versioning code.
2021-04-07 08:00:05,965 - DEBUG - xml:open_file:233 - Opening file /home/ppwy758/.var/app/org.gnome.GTG/data/gtg/gtg_tasks.xml
2021-04-07 08:00:05,968 - DEBUG - xml:open_file:233 - Opening file /home/ppwy758/.var/app/org.gnome.GTG/data/gtg/tags.xml
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 444, in register_backend
    backend.this_is_the_first_run(None)
  File "/app/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 156, in this_is_the_first_run
    tree = versioning.convert(old_path, self.datastore)
  File "/app/lib/python3.8/site-packages/GTG/core/versioning.py", line 79, in convert
    new_task = convert_task(task, ds)
  File "/app/lib/python3.8/site-packages/GTG/core/versioning.py", line 261, in convert_task
    new_content.text = et.CDATA(convert_content(content.text))
  File "src/lxml/etree.pyx", line 3099, in lxml.etree.CDATA.__cinit__
ValueError: ']]>' not allowed inside CDATA
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'

**Comment by niconil** [comment]
ok i catch it !
in the text of one of my task i have few lines of a XML file. and in this few line i have the forbidden sequence : ']]>'
i remove one closing bracket and conversion of my data can be done, and GTG 0.5 is launched on my desktop !

maybe check that this sequence ']]>' is not present in the text of the task.

**Comment by diegogangl** [comment]
Glad to hear, did you have some task in the previous version with that `]]>` character?
