### ISSUE TITLE
new version broke tasks

### ISSUE THREAD

**Issue by caligulanorris** [getting-things-gnome/gtg#697]
i updated to the most recent version my GTG with flatpak and tasks dont show up anymore.
i have backup of these.
so i wiped the data folder in .var and reinstalled GTG.

the software runs again, with default tasks.
having a look at the data files i noticed a lot of changes, xml version has changed, gtg_data.xml is a new file containing the tasks.
how can i migrate that so that my old xml gtg_tasts.xml and gtg_tags.xml work in here?

**Comment by Neui** [comment]
To my knowledge, place the old `gtg_tasks.xml` in there, delete (or move out) the default `gtg_data.xml`, so GTG should find the old one but not the new one and it should convert on first start. Don't forget to make backups.

**Comment by caligulanorris** [comment]
ok tried it, it converts the old tasks projects and tags in a new gtg_data.xml
but i get this error about a tag already existing.

```
➜  ~ flatpak run org.gnome.GTG
GNOME keyring not found, passwords will be not stored after restarting GTG
2021-08-18 11:42:35,687 - WARNING - backend_localfile:initialize:118 - Found old file. Running versioning code.
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 459, in register_backend
    source.initialize(connect_signals=False)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 822, in initialize
    self.backend.initialize()
  File "/app/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 135, in initialize
    self.datastore.load_search_tree(self.search_tree)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 280, in load_search_tree
    self.new_search_tag(name, query, tag_attrs, tid, False)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 144, in new_search_tag
    self._add_new_tag(name, tag, search_filter, parameters,
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 108, in _add_new_tag
    raise IndexError(f'tag {name} was already in the datastore')
IndexError: tag framadate was already in the datastore
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'

```
i had searches with the same name that some tags, i didn't expect it to put problems.
the CLI said  "tag framadate was already in the datastore"
so i tried to remove the saved searches in gtg_data.xml, and now it works fine \o/

still having this mystery line at every execution :
`GNOME keyring not found, passwords will be not stored after restarting GTG`

**Comment by nekohayo** [comment]
> i had searches with the same name that some tags, i didn't expect it to put problems.

Ah yeah, that's a weird implementation detail that, in fact, tags work essentially like searches (in a certain way) or vice versa so I guess having the exact same names in an old file format would have been problematic.

> so i tried to remove the saved searches in gtg_data.xml, and now it works fine \o/

Since the original reporter successfully worked around the problem and no more people reported it (it's pretty rare), I guess by now we can close it.

> still having this mystery line at every execution :
> GNOME keyring not found, passwords will be not stored after restarting GTG

I guess that is harmless, I think. If eventually you figure out what problem this might cause in practice, a separate ticket could be created for that.
