### ISSUE TITLE
GTG closes immediately and only flashes open afterwards when marking a task "Done" and opening its parent task, subsequently

### ISSUE THREAD

**Issue by laborhase** [getting-things-gnome/gtg#699]
Since carrying over my gtg_data.xml from Flatpak GTG v0.5 on Debian 10 (Gnome) to a fresh install of Debian 11 (Xfce), marking tasks as "Done" and then trying to open its parent tasks leads to immediate closing of GTG. Upon re-opening, the window only opens to close rightaway, again. `flatpak run org.gnome.GTG` only provides `GNOME keyring not found, passwords will be not stored after restarting GTG`. It does not seem to hang as no python process is running after closing and `flatpak kill org.gnome.GTG` provides `error: org.gnome.GTG is not running`. Deleting the "Done" task from gtg_data.xml makes it open fully again and the parent task can be opened as well. Upon copying the "Done" task back into gtg_data.xml, GTG opens but opening the parent task causes the crash again.

Done task:
```
    <task id="83ac2cc1-3e12-4bba-9bbd-85db96aadf4d" status="Done" uuid="83ac2cc1-3e12-4bba-9bbd-85db96aadf4d" recurring="False">
      <tags>
        <tag>369187e8-d85d-46dd-9d92-800b7a58ed75</tag>
      </tags>
      <title>ask Patricia for joint measurement with Shubham</title>
      <dates>
        <added>2021-08-14T00:12:59.350734</added>
        <modified>2021-08-23T13:30:33.006366</modified>
        <done>2021-08-23</done>
        <fuzzyDue/>
        <start>2021-08-23</start>
      </dates>
      <recurring enabled="false">
        <term>None</term>
        <updated_date>9999-12-30T00:00:00</updated_date>
      </recurring>
      <subtasks/>
      <content><![CDATA[@PFP-CP
asked Aug17]]></content>
    </task>
```

Parent task:
```
    <task id="140f6600-de28-4bca-9771-8bb1b7e65010" status="Active" uuid="140f6600-de28-4bca-9771-8bb1b7e65010" recurring="False">
      <tags>
        <tag>369187e8-d85d-46dd-9d92-800b7a58ed75</tag>
      </tags>
      <title>AFM on PFPCP conductivity</title>
      <dates>
        <added>2021-07-14T15:11:03.807067</added>
        <modified>2021-08-17T18:46:55.245569</modified>
        <done/>
        <fuzzyDue/>
        <fuzzyStart/>
      </dates>
      <recurring enabled="false">
        <term>None</term>
        <updated_date>9999-12-30T00:00:00</updated_date>
      </recurring>
      <subtasks>
        <sub>83ac2cc1-3e12-4bba-9bbd-85db96aadf4d</sub>
      </subtasks>
      <content><![CDATA[@PFP-CP
.5d; Patricia back Aug 12]]></content>
    </task>
```

**Comment by Neui** [comment]
I would assume that it would crash in C code because of some misuse, but not showing the "Segmentation fault" line seems weird. I am not sure if `flatpak run` forwards the exit code, but what does `flatpak run org.gnome.GTG; echo $?` say? Maybe look if you can somehow run gdb in it and try to run `bt` after it happened if it shows anything (preferably with gtk and glib symbols) to have a starting point.

**Comment by Leuug** [comment]
I'm having a similar problem, but I didn't tried to delete the "Done" task from gtg_data.xml because I couldn't find this file.

Running `flatpak run org.gnome.GTG; echo $?` I get:

`GNOME keyring not found, passwords will be not stored after restarting GTG`
`136`

**Comment by Neui** [comment]
> 136

136 - 128 = 8 (see Bash Exit codes, 128+n where n is the signal number), which means.. SIGFPE according to `man 7 signal` on my Ubuntu 20.04 machine. FPE means Floating-point exception, so some calculation went wrong (such as dividing by 0), although I think python should handle it correctly... So probably happening in C code.

I've never used flatpak, but try following https://docs.flatpak.org/en/latest/debugging.html (You also want the debugging symbols, so the org.gnome.Platform.Debug runtime)
Use the command like `gdb /usr/bin/python3 --args gtg` or where the gtg executable/script is. (Will check later the exact command, since it's rather late here now.) In gdb, type `run` to execute, and then `bt` when you get the prompt back to show where it was when it happened.

> but I didn't tried to delete the "Done" task from gtg_data.xml because I couldn't find this file.

Take a look at `~/.var/app/org.gnome.GTG/data/gtg/` for the flatpak version, it should be in there.

**Comment by Leuug** [comment]
I typed `gdb /usr/bin/python3` then `run /app/bin/gtg`. The application started but crashed and I got a prompt saying the application was not responding, I clicked "wait" a few times but the prompt came up again, then I clicked "force quit". I received this prompt:
![image](https://user-images.githubusercontent.com/58122451/130539406-2fbf87ed-6831-4f49-9206-690d95a465a6.png)

By typing `bt` i got:
![image](https://user-images.githubusercontent.com/58122451/130539477-6543fe37-29cd-43b1-81f4-0d6c86685b97.png)

**Comment by laborhase** [comment]
> I'm having a similar problem, but I didn't tried to delete the "Done" task from gtg_data.xml because I couldn't find this file.
> 
> Running `flatpak run org.gnome.GTG; echo $?` I get:
> 
> `GNOME keyring not found, passwords will be not stored after restarting GTG`
> `136`
Same here. 

`org.gnome.Platform.Debug` is not available on Flathub but had to install `org.gnome.Sdk` (along `org.gnome.GTG.Debug`) for any debugging. (I guess Debug is included in the Sdk?)

Upon `flatpak run --command=sh --devel org.gnome.GTG` then `gdb /usr/bin/python3` then `run /app/bin/gtg` I get a similar result.  GTG opens but freezes immediately (without closing) and in my case I get a little more talkative prompt:
```
Starting program: /usr/bin/python3 /app/bin/gtg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 100]
GNOME keyring not found, passwords will be not stored after restarting GTG
[New Thread 0x7ffff1d92700 (LWP 101)]
[New Thread 0x7ffff1591700 (LWP 102)]
[New Thread 0x7ffff0a03700 (LWP 103)]
[Thread 0x7ffff0a03700 (LWP 103) exited]
[New Thread 0x7ffff0a03700 (LWP 104)]
[New Thread 0x7fffe3fff700 (LWP 105)]
[Thread 0x7ffff0a03700 (LWP 104) exited]
[Thread 0x7fffe3fff700 (LWP 105) exited]
[New Thread 0x7fffe3fff700 (LWP 106)]
[New Thread 0x7ffff0a03700 (LWP 107)]
[New Thread 0x7fffe36de700 (LWP 108)]
[New Thread 0x7fffe2e3b700 (LWP 109)]
[New Thread 0x7fffe263a700 (LWP 110)]
[Thread 0x7fffe263a700 (LWP 110) exited]
[Thread 0x7fffe2e3b700 (LWP 109) exited]
[New Thread 0x7fffe263a700 (LWP 111)]
[New Thread 0x7fffe2e3b700 (LWP 112)]
[Thread 0x7fffe263a700 (LWP 111) exited]
[Thread 0x7fffe2e3b700 (LWP 112) exited]
[New Thread 0x7fffe2e3b700 (LWP 113)]
[New Thread 0x7fffe263a700 (LWP 114)]
[Thread 0x7fffe2e3b700 (LWP 113) exited]
[Thread 0x7fffe263a700 (LWP 114) exited]
[Thread 0x7fffe36de700 (LWP 108) exited]
[Thread 0x7fffe3fff700 (LWP 106) exited]
[New Thread 0x7fffe3fff700 (LWP 115)]
[New Thread 0x7fffe36de700 (LWP 116)]
[Thread 0x7fffe3fff700 (LWP 115) exited]
[New Thread 0x7fffe36de700 (LWP 117)]
[Thread 0x7fffe36de700 (LWP 116) exited]
[New Thread 0x7fffe3fff700 (LWP 118)]
[Thread 0x7fffe36de700 (LWP 117) exited]
[Thread 0x7fffe3fff700 (LWP 118) exited]
[New Thread 0x7fffe3fff700 (LWP 119)]
[New Thread 0x7fffe36de700 (LWP 120)]
[Thread 0x7fffe3fff700 (LWP 119) exited]
[Thread 0x7fffe36de700 (LWP 120) exited]
[New Thread 0x7fffe36de700 (LWP 121)]
[New Thread 0x7fffe3fff700 (LWP 122)]
[Thread 0x7fffe36de700 (LWP 121) exited]
[Thread 0x7fffe3fff700 (LWP 122) exited]
[New Thread 0x7fffe3fff700 (LWP 123)]
[New Thread 0x7fffe36de700 (LWP 124)]
[Thread 0x7fffe3fff700 (LWP 123) exited]
[Thread 0x7fffe36de700 (LWP 124) exited]
[New Thread 0x7fffe36de700 (LWP 125)]
[New Thread 0x7fffe3fff700 (LWP 126)]
[Thread 0x7fffe36de700 (LWP 125) exited]
[Thread 0x7fffe3fff700 (LWP 126) exited]
[New Thread 0x7fffe3fff700 (LWP 127)]
[New Thread 0x7fffe36de700 (LWP 128)]
[New Thread 0x7fffe263a700 (LWP 129)]
[Thread 0x7fffe36de700 (LWP 128) exited]
[New Thread 0x7fffe36de700 (LWP 130)]
[Thread 0x7fffe263a700 (LWP 129) exited]
[New Thread 0x7fffe263a700 (LWP 131)]
[Thread 0x7fffe263a700 (LWP 131) exited]
[Thread 0x7fffe36de700 (LWP 130) exited]
[New Thread 0x7fffe36de700 (LWP 132)]
[New Thread 0x7fffe263a700 (LWP 133)]
[Thread 0x7fffe36de700 (LWP 132) exited]
[Thread 0x7fffe263a700 (LWP 133) exited]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python3" received signal SIGFPE, Arithmetic exception.
0x00007ffff65affef in draw_strikethrough ()
   from /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
```

`bt` says:
```
#0  0x00007ffff65affef in draw_strikethrough ()
    at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#1  0x00007ffff65b0e42 in pango_renderer_part_changed ()
    at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#2  0x00007ffff65b100b in pango_renderer_set_alpha ()
    at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#3  0x00007ffff65b11bc in pango_renderer_default_prepare_run ()
    at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#4  0x00007ffff5bc365d in gtk_text_renderer_prepare_run ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff65b1495 in pango_renderer_draw_layout_line ()
    at /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
#6  0x00007ffff5bc3dbb in gtk_text_layout_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff5be467f in draw_text ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff5beb304 in gtk_text_view_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff5c512b4 in gtk_widget_draw_internal ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff59f6d37 in gtk_container_propagate_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff59f6e75 in gtk_container_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff5b75a92 in gtk_scrolled_window_render ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff59fcb03 in gtk_css_custom_gadget_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff5a027d8 in gtk_css_gadget_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff5b785b1 in gtk_scrolled_window_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff5c512b4 in gtk_widget_draw_internal ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff59f6d37 in gtk_container_propagate_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff59f6e75 in gtk_container_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff599ef29 in gtk_box_draw_contents ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff59fcb03 in gtk_css_custom_gadget_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff5a027d8 in gtk_css_gadget_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff59a1d01 in gtk_box_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff5c512b4 in gtk_widget_draw_internal ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff59f6d37 in gtk_container_propagate_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff59f6e75 in gtk_container_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff5c69eb3 in gtk_window_draw ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff5c512b4 in gtk_widget_draw_internal ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff5c60800 in gtk_widget_render ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff5ae3669 in gtk_main_do_event ()
    at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff63ca389 in _gdk_event_emit ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#31 0x00007ffff63d96a1 in _gdk_window_process_updates_recurse_helper ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#32 0x00007ffff63db341 in gdk_window_process_updates_internal ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#33 0x00007ffff63db538 in gdk_window_process_updates_with_mode ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#34 0x00007ffff72c7179 in _g_closure_invoke_va ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff72e07df in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff72e09c3 in g_signal_emit ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff63d320e in gdk_frame_clock_paint_idle ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#38 0x00007ffff63becad in gdk_threads_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#39 0x00007ffff73669d8 in g_timeout_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff7365e1f in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff73661c8 in g_main_context_iterate.constprop ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff7366293 in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff71306cd in g_application_run ()
    at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x00007ffff7774f75 in ffi_call_unix64 ()
    at /usr/lib/x86_64-linux-gnu/libffi.so.7
#45 0x00007ffff7774369 in ffi_call_int ()
    at /usr/lib/x86_64-linux-gnu/libffi.so.7
#46 0x00007ffff7471ed5 in pygi_invoke_c_callable ()
    at /usr/lib/python3.8/site-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so
#47 0x00007ffff7468a3c in pygi_function_cache_invoke ()
    at /usr/lib/python3.8/site-packages/gi/_gi.cpython-38-x86_64-linux-gnu.so
#48 0x00007ffff7d25710 in PyObject_Call ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#49 0x00007ffff7ce15aa in _PyEval_EvalFrameDefault ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#50 0x00007ffff7df5764 in _PyEval_EvalCodeWithName ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#51 0x00007ffff7df6851 in _PyFunction_Vectorcall ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#52 0x00007ffff7ce3346 in _PyEval_EvalFrameDefault ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#53 0x00007ffff7df5764 in _PyEval_EvalCodeWithName ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#54 0x00007ffff7df5a5e in PyEval_EvalCodeEx ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#55 0x00007ffff7df5a8b in PyEval_EvalCode ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#56 0x00007ffff7df5e97 in run_eval_code_obj ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#57 0x00007ffff7e5dcb1 in run_mod ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#58 0x00007ffff7e5e85f in pyrun_file ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#59 0x00007ffff7e6e4b5 in PyRun_SimpleFileExFlags ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#60 0x00007ffff7e71670 in Py_RunMain ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#61 0x00007ffff7e71aa6 in Py_BytesMain ()
    at /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
#62 0x00007ffff7ac5062 in __libc_start_main ()
    at /usr/lib/x86_64-linux-gnu/libc.so.6
#63 0x000055555555508e in _start ()
```

I force-quit GTG after `bt`.

**Comment by Leuug** [comment]
Oh, I didn't get the rest of the prompt because I clicked "force quit". I tried typing `bt` without clicking "force quit" and got the same errors.

**Comment by Neui** [comment]
> `org.gnome.Platform.Debug` is not available on Flathub but had to install `org.gnome.Sdk` (along `org.gnome.GTG.Debug`) for any debugging. (I guess Debug is included in the Sdk?)

I'm not very familiar with flatpak, I used `org.gnome.Platform.Debug` because the wikipage used runtime-name as the placeholder.
Also the command I thought was `gdb --args /usr/bin/python3 /app/bin/gtg` (just shortens `run /app/bin/gtg` to just `run`)

I was quickly able to reproduce that. Reverting the org.gnome.Platform runtime seems to work as a workaround: `flatpak update --commit=f111d6c1e912823e8db0f6ee8eebff82f9a8794b444e85e3aa801fe10e7b8e59 org.gnome.Platform//40` (broken commit is `02c742d62bdd4e4e7d89e7af2ea18b4117dda5339101aae885c6afeb0b1c49ae`; I used `flatpak remote-info --log flathub org.gnome.Platform//40` to determine the commit IDs)

It crashes a bit after startup since on startup it opens the previously opened tasks when you quit GTG, making the task window appear and causing the error again. You can open `~/.var/app/org.gnome.GTG/config/gtg/gtg.conf` in an text editor and remove the line `opened_tasks = ...` to stop GTG opening the error-causing task (but doesn't fix it).

It seems to error while trying to draw the strike through text (~~like this~~) for the done task. 
Looking around a bit, it seems some newer pango (doing text stuff) [broke strike-through with tabs it seems](https://gitlab.gnome.org/GNOME/pango/-/issues/604), and was fixed [2 days ago](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/425) in their development version.
Even happens with `gtk3-demo` (runnable inside that flatpak) with the Text View → Markup demo (you need to insert a tab yourself, space seems to work fine).

I'd guess that is related to that. Maybe wait until pango does a release and the runtime being updated, and use the old runtime for now.

**Comment by laborhase** [comment]
Using the reverting-runtime workaround and playing the waiting game with pango and the runtime update, I guess we can close the issue. Thank you so much for figuring this out!

**Comment by Neui** [comment]
On 2021-09-09 commit `8b41a8055e89e066ae8e647c4baaa6509234de32c745ae807307bcf4e69b05d0` for `org.gnome.Platform` has been released on flathub, but they still have the same buggy libpango (1.48.9 from what I can tell for both faulty commits). So the workaround still applies.
