### ISSUE TITLE
Not saving tasks 'Marked as Done' after closing

### ISSUE THREAD

**Issue by mizzunet** [getting-things-gnome/gtg#718]
I installed gtg by
```
meson -Dprefix=/usr/local/ systembuild
ninja -C systembuild install
```
Once any task is marked as done, the task will be moved to the 'Closed' tab as normal.
But as gtg closed and reopened, the tasks marked as Done will come back under the 'Open' tab. This seems like the data does not get retained.

But creating, editing, modifying tasks are retained after reopening though.

Moreover, launching gtg from repo root dir by `.launch.sh` works well.
How do I get logs?

Info:
Debian bookworm distro
GTG version v0.5-115-g3eacad13

**Comment by Neui** [comment]
Does the same happen if you replace `/home/missu/.git/gtg-0.5/tmp/default/xdg/data/gtg/gtg_data.xml` with `/home/missu/.local/share/gtg/gtg_data.xml` and then try in the `./launch.sh` version? (`mv /home/missu/.git/gtg-0.5/tmp/default/xdg/data/gtg/gtg_data.xml` with `/home/missu/.local/share/gtg/gtg_data.xml`)
If it then behaves the same, then some data is making it weird.

The "Tried to close tid ..." message refers trying to close the task window if you close a task, but no window has been found (in other words, harmless here). But the message is indeed somewhat misleading.

**Comment by mizzunet** [comment]
As you guessed, GTG failed to open with installed version ```gtg_data.xml```
```
 ~/.g/gtg-0.5  ./launch.sh
Running the development/debug version - using separate user directories
Your data is in the 'tmp' subdirectory with the 'default' dataset.
-----------------------------------------------------------------------
ninja: Entering directory `.local_build'
[6/7] Installing files.
Installing subdir /home/missu/.git/gtg-0.5/data/icons/hicolor to /home/missu/.git/gtg-0.5/.local_build/install/share/icons/hicolor
Installing /home/missu/.git/gtg-0.5/data/icons/hicolor/scalable/apps/org.gnome.GTGDevel.svg to /home/missu/.git/gtg-0.5/.local_build/install/share/icons/hicolor/scalable/apps
Installing /home/missu/.git/gtg-0.5/data/icons/hicolor/scalable/apps/backend_localfile.svg to /home/missu/.git/gtg-0.5/.local_build/install/share/icons/hicolor/scalable/apps
Installing /home/missu/.git/gtg-0.5/data/icons/hicolor/scalable/apps/org.gnome.GTG-symbolic.svg to /home/missu/.git/gtg-0.5/.local_build/install/share/icons/hicolor/scalable/apps
Installing /home/missu/.git/gtg-0.5/data/icons/hicolor/scalable/apps/org.gnome.GTG.svg to /home/missu/.git/gtg-0.5/.local_build/install/share/icons/hicolor/scalable/apps
Installing GTG/plugins/export.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing GTG/plugins/send-email.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing GTG/plugins/untouched-tasks.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing GTG/plugins/urgency-color.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing GTG/plugins/hamster.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing GTG/plugins/dev_console.gtg-plugin to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing data/org.gnome.GTGDevel.appdata.xml to /home/missu/.git/gtg-0.5/.local_build/install/share/metainfo
Installing data/org.gnome.GTGDevel.desktop to /home/missu/.git/gtg-0.5/.local_build/install/share/applications
Installing /home/missu/.git/gtg-0.5/docs/gtg.1 to /home/missu/.git/gtg-0.5/.local_build/install/share/man/man1
Installing /home/missu/.git/gtg-0.5/GTG/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG
Installing /home/missu/.git/gtg-0.5/.local_build/GTG/gtg to /home/missu/.git/gtg-0.5/.local_build/install/bin
Installing /home/missu/.git/gtg-0.5/.local_build/GTG/core/info.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/borg.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/clipboard.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/config.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/datastore.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/dates.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/dirs.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/firstrun_tasks.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/interruptible.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/keyring.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/networkmanager.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/requester.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/search.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/tag.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/task.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/xml.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/timer.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/treefactory.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/twokeydict.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/urlregex.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/watchdog.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/versioning.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core
Installing /home/missu/.git/gtg-0.5/GTG/core/plugins/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/plugins
Installing /home/missu/.git/gtg-0.5/GTG/core/plugins/api.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/plugins
Installing /home/missu/.git/gtg-0.5/GTG/core/plugins/engine.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/plugins
Installing /home/missu/.git/gtg-0.5/GTG/backends/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/backends/backend_localfile.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/backends/backend_signals.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/backends/generic_backend.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/backends/periodic_import_backend.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/backends/sync_engine.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/application.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/colors.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/general_preferences.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/plugins.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/preferences.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/tag_completion.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/addpanel.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/backendscombo.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/backendstree.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/configurepanel.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/checkbox.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/import_tags.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/password.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/path.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/period.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/backends/parameters_ui/text.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/backends/parameters_ui
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/backend_infobar.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/cell_renderer_tags.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/delete_tag.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/delete_task.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/main_window.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/modify_tags.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/simple_color_selector.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/tag_context_menu.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/tag_editor.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/treeview_factory.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/browser/quick_add.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/backends.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/calendar.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/context_menus.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/general_preferences.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/help_overlay.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/main_window.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/modify_tags.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/plugins.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/preferences.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/style.css to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/data/task_editor.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/data
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/calendar.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/editor.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/taskview.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/recurring_menu.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/gtk/editor/text_tags.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor
Installing /home/missu/.git/gtg-0.5/GTG/plugins/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/task_str.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/templates.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/description_pocketmod.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/description_sexy.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/description_simple.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/description_statusrpt.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/description_textual.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/graphics_pocketmod.svg to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/script_pocketmod to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/template_pocketmod.tex to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/template_sexy.html to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/template_simple.html to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/template_statusrpt.txt to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/template_textual.txt to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/thumbnail_pocketmod.png to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/thumbnail_sexy.png to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/thumbnail_simple.png to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/thumbnail_statusrpt.png to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/export/export_templates/thumbnail_textual.png to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/export/export_templates
Installing /home/missu/.git/gtg-0.5/GTG/plugins/send_email/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/send_email
Installing /home/missu/.git/gtg-0.5/GTG/plugins/send_email/sendEmail.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/send_email
Installing /home/missu/.git/gtg-0.5/GTG/plugins/untouched_tasks/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks
Installing /home/missu/.git/gtg-0.5/GTG/plugins/untouched_tasks/untouchedTasks.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks
Installing /home/missu/.git/gtg-0.5/GTG/plugins/untouched_tasks/untouchedTasks.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks
Installing /home/missu/.git/gtg-0.5/GTG/plugins/urgency_color/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/urgency_color
Installing /home/missu/.git/gtg-0.5/GTG/plugins/urgency_color/preferences.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/urgency_color
Installing /home/missu/.git/gtg-0.5/GTG/plugins/urgency_color/urgency_color.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/urgency_color
Installing /home/missu/.git/gtg-0.5/GTG/plugins/hamster/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/hamster
Installing /home/missu/.git/gtg-0.5/GTG/plugins/hamster/hamster.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/hamster
Installing /home/missu/.git/gtg-0.5/GTG/plugins/hamster/helper.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/hamster
Installing /home/missu/.git/gtg-0.5/GTG/plugins/hamster/prefs.ui to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/hamster
Installing /home/missu/.git/gtg-0.5/GTG/plugins/dev_console/__init__.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/dev_console
Installing /home/missu/.git/gtg-0.5/GTG/plugins/dev_console/console.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/dev_console
Installing /home/missu/.git/gtg-0.5/GTG/plugins/dev_console/window.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/dev_console
Installing /home/missu/.git/gtg-0.5/GTG/plugins/dev_console/utils.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/dev_console
Installing /home/missu/.git/gtg-0.5/GTG/plugins/dev_console/buffer.py to /home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/plugins/dev_console
Installing /home/missu/.git/gtg-0.5/.local_build/data/org.gnome.GTGDevel.service to /home/missu/.git/gtg-0.5/.local_build/install/share/dbus-1/services
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gtg'
Running custom install script '/usr/bin/meson --internal yelphelper install --subdir=docs/user_manual --id=gtg --installdir=share/help --sources=gtg-add-tag.page@@gtg-create-new-task.page@@gtg-complete-delete-dismiss-task.page@@gtg-date-parsing.page@@gtg-developer-resources.page@@gtg-edit-task.page@@gtg-faq.page@@gtg-main-window.page@@gtg-plugins.page@@gtg-preferences.page@@gtg-quickadd.page@@gtg-recurring-task.page@@gtg-search-intro.page@@gtg-search-syntax.page@@gtg-set-task-date.page@@gtg-shortcut-keys.page@@gtg-subtasks.page@@gtg-tag-color.page@@gtg-tags.page@@gtg-taskview.page@@index.page@@legal.xml --symlinks=true --media=figures/add-tag.png@@figures/ed
it_tag.png@@figures/gtg-icon.png@@figures/insert_subtask_icon.png@@figures/main_window.png@@figures/modify-tag.png@@figures/quick_tag_entry.png@@figures/search-icon.png@@figures/set_date_task_browser.png@@figures/set_date_task_open.png@@figures/subtasks.png@@figures/tag.png@@figures/task-toolbar-menu.png@@figures/workview.png'
GNOME keyring not found, passwords will be not stored after restarting GTG
Traceback (most recent call last):
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/datastore.py", line 463, in register_backend
    source.start_get_tasks()
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/datastore.py", line 700, in start_get_tasks
    self.backend.start_get_tasks()
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/backends/backend_localfile.py", line 185, in start_get_tasks
    task = xml.task_from_element(task, element)
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/core/xml.py", line 88, in task_from_element
    task.set_recurring_updated_date(datetime.fromisoformat(recurring_updated_date))
TypeError: fromisoformat: argument must be str
Traceback (most recent call last):
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/home/missu/.git/gtg-0.5/.local_build/install/lib/python3/dist-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'
```

**Comment by mizzunet** [comment]
Here's that problamatic file https://transfer.sh/a0qFtr/gtg_data.xml

**Comment by Neui** [comment]
Did you try to open the gtg_data.xml from a future version (v0.5-115-g3eacad13) to the "vanilla" 0.5 version? AFAIK I noticed that since some change v0.5 complains when you've opened (and saved) the data in a newer development version.

**Comment by mizzunet** [comment]
> Did you try to open the gtg_data.xml from a future version (v0.5-115-g3eacad13)
Oh my bad, that's right. :D

Let me try opening from v0.5-115-g3eacad13

**Comment by mizzunet** [comment]
The issue is happening on  v0.5-115-g3eacad13 started from source (by `./launch.sh`)

**Comment by Neui** [comment]
I found the issue, just a one line fix. You can run `git fetch origin pull/719/head && git checkout FETCH_HEAD` inside the repo (assuming you cloned with git) to test the change. To go back to the old git branch, use `git checkout master`.

**Comment by mizzunet** [comment]
>git fetch origin pull/719/head && git checkout FETCH_HEAD

That fixed it, awesome. Thanks :heart:

**Comment by mizzunet** [comment]
BTW, how do I uninstall v0.5-115-g3eacad13 and install this FETCH_HEAD's version(v0.5-118-gfbddc83f)?

I tried,
`meson -Dprefix=/usr/local/ systembuild`
`sudo ninja install` from systembuild
expecting it would replace 115 with 118, but that did not. So, is there a proper way to uninstall 115?

Also `sudo ninja uninstall` after reinstallation of 115, that uninstalled gtg, but once I `sudo ninja install` from 118's systembuild dir, gtg still is 115

**Comment by Neui** [comment]
The `sudo ninja install` should've replaced the files. Make sure GTG isn't running anymore (check the process list for python3 processes). Also does the fix work? Maybe the version string just wasn't updated for some reason...

**Comment by mizzunet** [comment]
A strange thing happens while installation, that is, `launch.sh` installs gtg into .localbuild right. And gtg appearing after `launch.sh` is `v0.5-117-g828c345d`

But when I open the gtg from `.localbuild/install/bin/gtg` the version is `v0.5-115-g3eacad13`.

Same with `systembuild`, so `sudo ninja install` still installing  `v0.5-115-g3eacad13`

No gtg or python processes were running in the background

**Comment by Neui** [comment]
> But when I manually open the gtg from .localbuild/install/bin/gtg, the version is v0.5-115-g3eacad13.

This is because of the environment. That script just "imports gtg" stuff, and python has a list of paths to check import from (think of like `PATH` variable, but python specific).

`python3 -c 'import sys; print("\n".join(sys.path))'` will print a list of paths it'll import from (in your current shell environment), check if there is any GTG folder with contents inside of them when you've uninstalled GTG, and delete any copies you find.

**Comment by mizzunet** [comment]
Thanks, worked!!!
I really appreciate helping and figuring out :+1:
