### ISSUE TITLE
Error : rgba_to_hex is not defined

### ISSUE THREAD

**Issue by flomine** [getting-things-gnome/gtg#755]
When launch gtd (git version get from aur PKGBUILD) on archlinux with clean profile. If I click on synchronization, I get following error.
Am I missing any dependency  ?

```
  Context: Global generic exception
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/site-packages/GTG/gtk/application.py", line 386, in open_backends_manager
      self.open_edit_backends()
    File "/usr/lib/python3.10/site-packages/GTG/gtk/application.py", line 484, in open_edit_backends
      self.backends_dialog = BackendsDialog(self.req)
    File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 75, in __init__
      self._create_widgets_for_treeview()
    File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 196, in _create_widgets_for_treeview
      self.backends_tv = BackendsTree(self)
    File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py", line 50, in __init__
      self.refresh()
    File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py", line 67, in refresh
      self.on_backend_state_changed(None, backend.get_id())
    File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py", line 125, in on_backend_state_changed
      color = rgba_to_hex(color)
  NameError: name 'rgba_to_hex' is not defined
  
  
  Getting Things GNOME! v0.5-158-g4b02c437-dirty
  CPython 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
  GTK 3.24.31, GLib 2.70.1
  PyGLib 3.42.0, PyGObject 3.42.0
  Linux-5.10.90-1-lts-x86_64-with-glibc2.33
```

**Comment by Neui** [comment]
No, there was some changes to the code regarding colours, but the change wasn't tested because it wasn't used by anything at the time until the caldav support was merged.

Created PR which fixes the issue.

If you want to test the change now until it is merged, simply open `/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendstree.py` in an plain text editor, and on line 23 change at the end of that line from `rgb_to_hex` to `rgba_to_hex`.
