### ISSUE TITLE
AUR build

### ISSUE THREAD

**Issue by zeddo123** [getting-things-gnome/gtg#767]
I've been having issues installing `gtg` and `gtg-git` from the AUR. Even though `python-liblarch` is installed on my system, I get this error:
```bash
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'liblarch')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.10/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.10/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.10/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zeddo/.cache/yay/gtg-git/src/gtg/tests/tools/test_tags.py", line 21, in <module>
    from GTG.core.tag import extract_tags_from_text, parse_tag_list
  File "/home/zeddo/.cache/yay/gtg-git/src/gtg/GTG/core/tag.py", line 30, in <module>
    from liblarch import TreeNode
ModuleNotFoundError: No module named 'liblarch'
```

**Comment by diegogangl** [comment]
Is it installed for Python 3.10? Try running a python interpreter and import liblarch

**Comment by zeddo123** [comment]
Thanks @diegogangl!
I erased the cached build of `python-liblarch` and reinstalled it.
