### ISSUE TITLE
Export plugin PDF template not working

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#831]
Export plugin PDF template is not working because it lacks `pdf90` and `pdfnup` commands. They are are required by `GTG/plugins/export/export_templates/script_pocketmod`, but are not visible as dependencies in plugin description: 

https://github.com/getting-things-gnome/gtg/blob/4bd89aa55cb15b5cd077afd5fc08c2718ef51528/GTG/plugins/export.gtg-plugin#L9

nor in documentation:

https://github.com/getting-things-gnome/gtg/blob/master/README.md#solving-dependencies-for-plugins-optional

I have found only the latter:

https://pypi.org/project/pdfnup/

but I can't install it under Ubuntu 20.04 via pip because of an error:

```
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6jendb1c/pdfnup/setup.py", line 7, in <module>
        import ez_setup
      File "/tmp/pip-install-6jendb1c/pdfnup/ez_setup.py", line 94
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
```

**Comment by kocio-pl** [comment]
It looks like this should be easy to fix, since both were only wrappers for pdfjam and were dropped in 3.02: 

https://github.com/rrthomas/pdfjam#-wrapper-scripts-no-longer-included-here
