### ISSUE TITLE
Internal error when I try to add a synchronization service

### ISSUE THREAD

**Issue by environmentalcode0** [getting-things-gnome/gtg#846]
When I click on the '+' button to add a CalDAV service, I get the following error: 

```
**Context:** Global generic exception

python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'applications-internet' not present in theme Adwaita (0)


**Software versions:**
* Getting Things GNOME! v0.6-1-g0ddca321-dirty
* CPython 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
* GTK 3.24.31, GLib 2.70.2
* PyGLib 3.42.0, PyGObject 3.42.0
* Linux-5.16.11-arch1-2-x86_64-with-glibc2.35
```

**Comment by diegogangl** [comment]
That's weird, that icon is definitely in adwaita. Are you using any other themes or icon sets?

**Comment by environmentalcode0** [comment]
I'm using the default Adwaita icons and theme from the ArchLinux repository and I don't have any other themes or icon sets installed.

**Comment by nekohayo** [comment]
Could it be that this icon disappeared from the very latest icon themes (that Arch certainly provides, btw) and Fedora (or flatpak) users haven't been encountering _yet_? Because so far we did have this icon showing up without errors when we tested, but personally I'm on an old version of Fedora.

Maybe the code also needs to have a method to generically test for the presence or absence of icons and display a fallback if needed, or should it just traceback and let the traceback catcher catch it so that we actually know there's an issue (like here)?

**Comment by environmentalcode0** [comment]
I managed to solve the issue. I was using the Adwaita icon theme v42 (which will ship with Gnome 42) so I downgraded to the previous version and now it works. But that's strange: why doesn't v42 have that icon in particular? Actually I shouldn't ask it here, but it's definitely something you want to know since 42 will ship in the coming weeks and maybe other users will face this error.

**Comment by diegogangl** [comment]
@environmentalcode0 glad to hear it's fixed, and thanks for the heads up! It is an old style icon though, from the Gtk 2.x days

**Comment by nekohayo** [comment]
I guess for now the only defensive line is keeping the flatpak at version 41, but we will need to change that code for the next release (if someone here wants to provide a patch for this, might be a good thing to also check the other icons throughout the code while we're at it) as the 41 flatpak runtime won't be there forever...

**Comment by samyak-jain** [comment]
The fix for this seems pretty simple if we decide to just change the icon. I have a fork here https://github.com/samyak-jain/gtg/tree/change-icon that is working for me. I am using the network-server icon right now. Would love to hear any thoughts on which one we should go with if we do plan changing the icon.
