### ISSUE TITLE
flatpak 0.6 fatal error

### ISSUE THREAD

**Issue by worsco** [getting-things-gnome/gtg#848]
Any advice on troubleshooting flatpak version of the 0.6 release?  0.5 worked fine.  This is the error from the 0.6 flatpak:

```
$ flatpak run org.gnome.GTG
2022-03-05 10:32:24,284 - WARNING - general_preferences:get_default_editor_font:89 - Using deprecated but still working font way (UnicodeDecodeError('utf-8', b'p\xb4\xb3\xec\\U 9', 1, 2, 'invalid start byte'))
2022-03-05 10:32:24,765 - ERROR - application:do_activate:153 - Exception during activation
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
2022-03-05 10:32:29,085 - INFO - errorhandler:handle_response:163 - Going to exit because either of fatal error or user choice

```

**Comment by Neui** [comment]
You need to disable the Hamster plugin (this unfortunately occurs if you don't have the hamster plugin installed), see https://github.com/getting-things-gnome/gtg/issues/770#issuecomment-1030678522

**Comment by worsco** [comment]
Thank you. `vim ~/.var/app/org.gnome.GTG/config/gtg/gtg.conf` and removing `,hamster` from the `enabled =` list in section `[plugins]` fixed the start-up issue.

**Comment by jorgeecardona** [comment]
In my case it was not enough to remove `hamster` from the list of enabled plugins. GTG would open just once and the same fatal error would appear after. Somehow `hamster` was enabled again. Adding `hamster` to the list of disabled plugins work.
