### ISSUE TITLE
GTG Unable to Start After Recent Install

### ISSUE THREAD

**Issue by martinlastname** [getting-things-gnome/gtg#877]
I just installed GTG via Flatpak, did some poking around, updated my system, and now can no longer launch even after reinstalling and rebooting. What exactly I did (to the best of my memory from 10m ago):

1. Installed GTG
2. Ran `flatpak update` and `yay -Syu` in separate terminals
3. Opened GTG
4. Read some of the tutorial tasks
5. Opened the synchronization menu and started adding a CalDAV sync (stopped at the login screen)
6. flatpak and yay finished updating
7. I got a notification that core system packages had been updated and warranted a reboot
8. Rebooted
9. GTG crashes on startup with the following error

> **Context:** Startup
> 
> ```python-traceback
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 110, in do_startup
>     for backend_dic in BackendFactory().get_saved_backends_list():
>   File "/app/lib/python3.9/site-packages/GTG/backends/__init__.py", line 143, in get_saved_backends_list
>     module = self.get_backend(settings.get('module'))
>   File "/app/lib/python3.9/site-packages/GTG/core/config.py", line 164, in get
>     raise ValueError(
> ValueError: No valid configuration value or default value was found for %s in %s
> ```
> 
> **Software versions:**
> * Getting Things GNOME! v0.6
> * CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
> * GTK 3.24.33, GLib 2.70.5
> * PyGLib 3.42.0, PyGObject 3.42.0
> * Linux-5.17.1-arch1-1-x86_64-with-glibc2.33

I tried rebooting again, didn't fix it. I tried reinstalling via flatpak, same error.

If I try to launch GTG again without closing the original error dialogue, I get this error instead:

> **Context:** Global generic exception
> 
> ```python-traceback
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 144, in do_activate
>     if self._check_exception():
>   File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 195, in _check_exception
>     GLib.Source.remove(self._exception_dialog_timeout_id)
> TypeError: Argument 0 does not allow None as a value
> ```
> 
> **Software versions:**
> * Getting Things GNOME! v0.6
> * CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
> * GTK 3.24.33, GLib 2.70.5
> * PyGLib 3.42.0, PyGObject 3.42.0
> * Linux-5.17.1-arch1-1-x86_64-with-glibc2.33

**Comment by patrickbolle** [comment]
Am getting this exact same error on Debian.

Here is my logs:
```
**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 110, in do_startup
    for backend_dic in BackendFactory().get_saved_backends_list():
  File "/app/lib/python3.9/site-packages/GTG/backends/__init__.py", line 143, in get_saved_backends_list
    module = self.get_backend(settings.get('module'))
  File "/app/lib/python3.9/site-packages/GTG/core/config.py", line 164, in get
    raise ValueError(
ValueError: No valid configuration value or default value was found for %s in %s
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.33, GLib 2.70.5
* PyGLib 3.42.0, PyGObject 3.42.0
* Linux-5.10.0-11-amd64-x86_64-with-glibc2.33
```

**Comment by nekohayo** [comment]
Hi @patrickbolle & @martinlastname, it's unclear to me what the causes might be from your preliminary investigation above (thanks for that though!), but I'm starting to suspecting this might be the same issue as #845. Could you see if this has anything to do with your session keyring not being unlocked?
