### ISSUE TITLE
Crash trying to edit task with Hamster plugin active: "Expected Gio.MenuItem, but got gi.repository.Gtk.ModelButton"

### ISSUE THREAD

**Issue by piio** [getting-things-gnome/gtg#888]
Hi,

In newest version of gtg I got error when trying to edit task:

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/gtk/browser/main_window.py", line 1120, in on_edit_active_task
    self.app.open_task(tid)
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/gtk/application.py", line 567, in open_task
    editor = TaskEditor(requester=self.req, app=self, task=task,
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/gtk/editor/editor.py", line 262, in __init__
    self.pengine.onTaskLoad(self.plugin_api)
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/core/plugins/engine.py", line 242, in onTaskLoad
    plugin.instance.onTaskOpened(plugin_api)
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/plugins/hamster/hamster.py", line 200, in onTaskOpened
    plugin_api.add_menu_item(task_menu_item)
  File "~/.archive/src/gtg/.local_build/install/local/lib/python3.10/site-packages/GTG/core/plugins/api.py", line 155, in add_menu_item
    menu.append_item(item)
TypeError: argument item: Expected Gio.MenuItem, but got gi.repository.Gtk.ModelButton
```

**Software versions:**
* GTG (debug version) v0.6-59-g188b5f65
* CPython 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
* GTK 3.24.31, GLib 2.72.0
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.18.0-0.rc4.20220429git38d741cb70b3074.37.fc37.x86_64-x86_64-with-glibc2.35.9000

**Comment by nekohayo** [comment]
Does this still happen with the latest git `master` version?

**Comment by piio** [comment]
Yes, it happens with latest master version

**Comment by piio** [comment]
Hi!

No, this issue don't occur at newest master version.
I have now another bug connected with hamster - https://github.com/getting-things-gnome/gtg/issues/996

**Comment by nekohayo** [comment]
Thank you for the update, let's close this one here as indirectly fixed then.
