### ISSUE TITLE
CalDAV OAUTH2 authentication support

### ISSUE THREAD

**Issue by azmeuk** [getting-things-gnome/gtg#911]
Some DAV providers disable the `Basic` authentication method (i.e. username+password) in favor of the `Bearer` method (i.e. tokens).

Trying to connect to such a provider with GTG results in this traceback being displayed, but no in-app message indicating something is going wrong:

```python
Exception in thread Thread-1 (__backend_startup):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/GTG/core/datastore.py", line 499, in __backend_startup
    backend.start_get_tasks()
  File "/usr/lib/python3.10/site-packages/GTG/core/datastore.py", line 694, in start_get_tasks
    self.backend.start_get_tasks()
  File "/usr/lib/python3.10/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/usr/lib/python3.10/site-packages/GTG/backends/periodic_import_backend.py", line 79, in start_get_tasks
    self._start_get_tasks()
  File "/usr/lib/python3.10/site-packages/GTG/backends/periodic_import_backend.py", line 98, in _start_get_tasks
    self.do_periodic_import()
  File "/usr/lib/python3.10/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/usr/lib/python3.10/site-packages/GTG/backends/backend_caldav.py", line 111, in do_periodic_import
    self._do_periodic_import()
  File "/usr/lib/python3.10/site-packages/GTG/backends/backend_caldav.py", line 139, in _do_periodic_import
    self._refresh_calendar_list()
  File "/usr/lib/python3.10/site-packages/GTG/backends/backend_caldav.py", line 218, in _refresh_calendar_list
    principal = self._dav_client.principal()
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 362, in principal
    self._principal = Principal(client=self, *largs, **kwargs)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 404, in __init__
    cup = self.get_property(dav.CurrentUserPrincipal())
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 175, in get_property
    foo = self.get_properties([prop], **passthrough)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 198, in get_properties
    response = self._query_properties(props, depth)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 142, in _query_properties
    return self._query(root, depth)
  File "/usr/lib/python3.10/site-packages/caldav/objects.py", line 160, in _query
    ret = getattr(self.client, query_method)(
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 410, in propfind
    return self.request(url or self.url, "PROPFIND", props,
  File "/usr/lib/python3.10/site-packages/caldav/davclient.py", line 557, in request
    raise NotImplementedError("Auth method %s not supported yet" % auth_type)
NotImplementedError: Auth method bearer not supported yet
```

Fixing this probably depends on [python-caldav](https://github.com/python-caldav/caldav/issues/119) OAUTH support, but it has not been implemented yet. However I suppose that some UX work would probably be needed on the GTG side then.

I suggest to:
- display a comprehensible error message in the application when this `NotImplementedError` is met
- allow CalDAV OAUTH2 authentication support when it is ready on the caldav lib side

What do you think?

**Comment by pentux-GitHub** [comment]
Status update from auditing the caldav library: bearer authentication may actually already work. Since at least caldav 1.4.0 (the version pinned in our flatpak), the client negotiates auth with the server and automatically switches to `HTTPBearerAuth(password)` when the server advertises bearer — meaning the token can simply be pasted into the password field. If someone with an OAuth-only provider can test this on current master, this issue might reduce to two small UX items: documenting it, and showing an in-app error instead of a raw traceback when auth fails (the original report's second half).
