### ISSUE TITLE
Fatal internal error with the `untouched_tasks` plugin (no hamsters involved)

### ISSUE THREAD

**Issue by LuigiWriter** [getting-things-gnome/gtg#912]
#893 was the only instance of this error message that seemed close, however "Hamster" does not occur in my gtg.conf on any line in `.var/app/org.gnome.GTG/config/gtg/gtg.conf`

Version 0.6 dl.flathub.org which worked just fine for at least 3 months then this. I am unaware of any updates to it at the end of June 2022. If there was one it could be the source of this error.

My temporary fix has been to return to Ubuntu 0.3.1-4 because even installing 0.6 directly from flatpack flathub on 2022-07-07 I still get the Fatal internal error message. Unfortunately Flathub no longer offers 0.5 to fall back to.

The Fatal internal error happens whether launched from launchpad or terminal.

**Here is result of running flatpak run org.gnome.GTG -d**
```
luigiwriter@luigi_Envy14:~/.var/app/org.gnome.GTG/config/gtg$ flatpak run org.gnome.GTG -d
2022-07-04 14:54:49,054 - DEBUG - application:set_logging:669 - Debug output enabled.
Gtk-Message: 14:54:49.110: Failed to load module "canberra-gtk-module"
2022-07-04 14:54:49,115 - DEBUG - init:init:60 - Backends found: ['backend_localfile', 'backend_caldav', 'backend_signals']
2022-07-04 14:54:49,638 - DEBUG - xml:open_file:215 - Opening file /home/luigiwriter/.var/app/org.gnome.GTG/data/gtg/gtg_data.xml
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child 58d1ce8c-a006-495d-a408-615db2022ee2 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child b4bdd21b-a801-4e81-acd5-2faf153eb032 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child dd0b8c59-778a-4b8c-9b1c-668ea1e74c7c to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child 3d637cdc-73f2-4b92-8cf3-e81b18a613cb to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child bfe3572e-268b-46ee-9bc0-ffcd3136b033 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child ad28e098-90e6-49cd-9b85-70aa237e6975 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child 1e969d57-6ac3-4b90-85a7-2aa00d146bff to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child 22198eae-e104-455f-b93b-3eb59500f54f to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,669 - DEBUG - task:add_child:678 - adding child 179398d3-7a1d-4245-8605-d9591fa13a75 to task 58d1ce8c-a006-495d-a408-615db2022ee2
2022-07-04 14:54:49,698 - DEBUG - task:add_child:678 - adding child 7de19fce-7862-43a9-bf25-09f26cdac074 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,698 - DEBUG - task:add_child:678 - adding child e54871f9-d0ec-4004-8ff8-f550974a1eff to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child f6184319-3b4c-4027-a52d-6c2b1f025eb1 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child 9f694ffb-de0f-4e49-8d70-5c1288ab9eb9 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child 3fc93eca-e480-4bc1-9340-ce9225184b75 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child f87d61b9-30ad-43d3-ac08-3ed389fdf5c0 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 0ffda5ec-550c-4d81-b96d-106e81f2c1ca to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 2658c68b-1282-452c-850e-a84f5d0e00e5 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 276d7a73-05c0-4bf0-85ce-8bfea5bf7eb4 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 4e3b7d2c-495d-45fa-bbb7-6ba07b4eb609 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child c3656665-003e-4b9c-b6fc-6f8b135ce8a1 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,715 - DEBUG - task:add_child:678 - adding child a4fde0c8-88a4-4389-b4ca-9766eb0a2464 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,735 - DEBUG - task:add_child:678 - adding child 44fffaad-25c4-4dad-8f84-32de89a07ffa to task c3656665-003e-4b9c-b6fc-6f8b135ce8a1
2022-07-04 14:54:49,750 - DEBUG - task:add_child:678 - adding child 40367aa7-49ae-45a5-a4e6-745f437207bd to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,750 - DEBUG - task:add_child:678 - adding child 57d8ac82-a296-47d4-a258-a21886bc98e7 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child b9691b2f-37b5-485b-a742-78a3dfb021f3 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child 0abd2e7a-6bed-4b36-86a6-24c7c2992c72 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child e699394f-077c-4576-8639-5678c62aee28 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child 43269628-74be-4bfb-b856-0598aec7f734 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,792 - DEBUG - task:add_child:678 - adding child 7af4ec05-c310-4b8c-aaeb-ebf7ca6a686e to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,793 - DEBUG - task:add_child:678 - adding child 01c4256c-5caf-4bfa-bdb0-c176abc62507 to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,793 - DEBUG - task:add_child:678 - adding child fbf61efa-2ae1-4009-9042-a1fc2d65aca9 to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,795 - DEBUG - task:add_child:678 - adding child 9801b896-af53-43d5-abe2-00a4fc2bdab6 to task c427cda9-e3d2-4922-ac32-41f711e2b39f
2022-07-04 14:54:49,798 - DEBUG - task:add_child:678 - adding child c427cda9-e3d2-4922-ac32-41f711e2b39f to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 986b8544-f46c-4e63-9a52-feb68bc3b7d1 to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 0fe9f1aa-8258-4dbd-ab24-6ae3146d7146 to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 4d9e98c8-d7b5-415c-8e98-7c3438f72c3b to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child a0786844-fff9-4fef-b50d-0ef9165adb7f to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child 12fdad07-c7e7-4638-b294-6509f4131b3a to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child 74f3c76b-3e14-4058-a299-b347f5b6b768 to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child f58ee939-b6e8-464a-8a34-0911fad443ee to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 103bda14-4cfd-4ac8-9bc1-793b8e4b90d0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 54224fcc-e4da-496d-b1d4-68e93127845c to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 5b68ad82-34c7-46be-837c-abf7e7e3dea0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child f2f9fb7b-05c7-4ab5-a1ed-34d259b891c0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,929 - DEBUG - task:add_child:678 - adding child af4644f3-21f5-47f9-8cd3-bff837e5b703 to task 103bda14-4cfd-4ac8-9bc1-793b8e4b90d0
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child ee92af88-535d-4b79-9149-0508255a63b8 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 14ae3d02-bce1-4bee-aeed-b5d088b8d84e to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 5cb19136-0104-4f41-b9a4-7c8f2720e22f to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 7c544480-3a80-4760-92aa-824624d765c8 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child b51a837c-d79f-455b-b54f-ca18c73b3867 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,975 - DEBUG - task:add_child:678 - adding child 56626b44-052e-4cc6-ae0b-3177033def39 to task 83691d27-990d-46df-9ef4-fe451907d587
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child dc4eb8f2-c2db-4537-aac4-e7be3dfb7964 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 622a3893-3b6e-489e-a5f1-f89ce35d4463 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 3e3ba47b-211e-4c08-9c03-ebf4201bb8f8 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child ad826779-bf13-4073-8667-6121c82b21c3 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 73421438-add5-4063-9638-2dceb2eae4bc to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,014 - DEBUG - task:add_child:678 - adding child 495cc797-8ea0-4e0c-8640-e29f100a8cc3 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child d38e25a1-5ab0-49b6-9abb-5280c6780310 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 62997a6a-3e96-4724-98e2-37931eafa836 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child cb9b3a6d-325d-4a95-be69-dbff32bbd2f7 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 8537ce5b-9d8d-4f63-bb02-72bf5cf5be21 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 0f6c07f7-b0ef-4732-8b77-cb6638a229c2 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,104 - DEBUG - task:add_child:678 - adding child 3f3f017f-4d74-429a-ad93-ba59c64bdd47 to task 5b16f3d0-4d69-41cc-ae27-cfef86971e54
2022-07-04 14:54:50,158 - DEBUG - task:add_child:678 - adding child 0be32446-a3fe-445c-968a-428c62d9a312 to task 5841651f-6957-4050-aecd-5c92a7fb797d
2022-07-04 14:54:50,160 - DEBUG - task:add_child:678 - adding child a9681098-b907-4518-bfaf-9de04774262e to task fa35d7b3-017d-475c-aab7-d450b0f9bac8
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child 44b392db-82af-47b1-b992-8f552a758c39 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child f3bad687-bfd6-4f5d-a219-a72e9e7998c3 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child 66792881-53dd-4272-a34d-b0bfc8486bab to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child c5486366-49ee-400c-a79c-f61741cd84c6 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child 82a0c852-f517-41af-aa3c-2ec1b94196ee to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child ec8fb13d-7f35-45ca-a0cd-1912ac1f3988 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child 74323f4f-6357-455a-820e-83a9346f75df to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:51,129 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Label object at 0x7f4af89e9900 (GtkLabel at 0x55aab4ac53f0)>
2022-07-04 14:54:51,130 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Image object at 0x7f4af89e5a00 (GtkImage at 0x55aab4af4b50)>
2022-07-04 14:54:53,110 - DEBUG - untouchedTasks:add_untouched_tag:105 - Starting process for adding @UnTouched
2022-07-04 14:54:53,130 - ERROR - application:do_activate:153 - Exception during activation
```

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 72, in activate
    self.preferences_apply()
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 173, in preferences_apply
    self.add_untouched_tag()
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 117, in add_untouched_tag
    if new_time < today:
TypeError: can't compare datetime.datetime to datetime.date
```

```
2022-07-04 14:55:05,409 - DEBUG - errorhandler:handle_response:161 - handling response 1
2022-07-04 14:55:05,410 - INFO - errorhandler:handle_response:163 - Going to exit because either of fatal error or user choice
```

**Other actions during troubleshooting**
```
$ sudo apt update
$ sudo apt upgrade
$ flatpak update
$ sudo apt autoremove
```
**Platform information**
Computer
* Processor Intel(R) Core(TM) i5 CPU M 580 @ 2.67GHz
* Memory 3824MB (2689MB used)
* Machine Type Notebook
* Operating System Ubuntu 18.04.5 LTS
Operating System Version
* Kernel Linux 5.4.0-47-generic (x86_64)
* Version 51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020
* C Library GNU C Library / (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27
* Distribution Ubuntu 18.04.5 LTS

I Have been delaying moving to 20.04 LTS until some important business is completed wanting to avoid any teething problem interruptions. 

Any questions or requests for further tests welcome.
I appreciate you reviving this so useful app.

**Comment by LuigiWriter** [comment]
Please ignore my comment on "baloo and bash," for now. I have a lot more reading to do to understand the levels between the GUI and the Shell. If anyone can point me to a schematic, flow-chart or map it would help me report situations more clearly,

**Comment by LuigiWriter** [comment]
Scanned all my data with ClamTk to ensure my data was not causing the failure.
Uninstalled 0.6 dl.flathub.org
Tried installing directly from Flathub
```
:~$ flatpak install flathub org.gnome.GTG
Looking for matches…
org.gnome.GTG permissions:
    ipc        network                      fallback-x11       wayland
    x11        system dbus access [1]
    [1] org.freedesktop.login1
        ID                            Branch          Op         Remote          Download
 1. [✓] org.gnome.GTG.Locale          stable          i          flathub         5.4 kB / 251.7 kB
 2. [✓] org.gnome.GTG                 stable          i          flathub         2.7 MB / 3.3 MB
Installation complete.
```
It fails with the same 
_GTG Fatal internal error_

I wanted to drop back to 0.5 but flathub only offers 0.6. 
Installed 0.3.1 from Ubuntu Software
It loads with all my tasks from gtg_tasks.xml from ~/.local/share/gtg/
And no errors.
Presently I am too pressed by other things to even attempt the GTG 0.6 release candidate.
I look forward to the roll out of the stable version.

Is there any way of getting flathub to offer 0.5 as an option until Flathub's and Ubuntu's 0.6 stops being so fatalistic.
Hope the Release Candidate comes through with flying colors!!

**Comment by Neui** [comment]
It looks like the `untouched_tasks` plugin is causing the issue. You can try the same instructions for disabling `hamster` but for `untouched_tasks` instead.

If you want to downgrade to v0.5 flatpak you can use something like `flatpak update --commit=06ff3781b36c05a5c4b8863035b6f1c0609f121110484af48fb7d61d1b683f9b org.gnome.GTG` (and `flatpak mask org.gnome.GTG` to not accidentally update it again). ([Source](https://unix.stackexchange.com/a/552700))

**Comment by LuigiWriter** [comment]
Thank you, I discovered it was not a flatpak but a snap version of 0.6 I was using.
When I installed the flatpak 0.6 it was unable to access the internal filesystem.
See
[Bug]: Accessing Internal Storage from Flatpak Apps #4985 https://github.com/flatpak/flatpak/issues/4985
and
[Question] "Accessing External storage from Flatpak apps https://github.com/flatpak/flatpak/issues/2713"

I will try your suggestion, but with Flatpak's present problem affecting apps like GThumb and Dolphin as well I am not too optimistic. I had to go back to the Ubuntu versions of those as well.

0.3.1 from Ubuntu Software is working with out all the improvements, but at least working. Ah, well. 
I have posted a new issue about the flatpak suspected problem as an alert. As an Linux Auteur I hope I am providing the best information with which you can work.

**Comment by Neui** [comment]
My initial technical look:

Surrounding code:
https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/plugins/untouched_tasks/untouchedTasks.py#L117

As seen `today` is a `datetime.datetime`, so `new_time` must be the `datetime.date`. `datetime.date + datetime.timedelta` still results in `datetime.date`, so `modified_date` was `datetime.date`.
Actually, it is a `GTG.core.dates.Date` because it is [created into one](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/core/task.py#L254), but for the `+` operator with `timedelta`, it [uses the underlying `dt_value`](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/core/dates.py#L216-L219), which means `dt_value` is a `datetime.date` here.
`Task.set_modified()` is called by [`task_from_element`](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/core/xml.py#L35=), however it is soon overwritten by a `sync()` by the `set_recurring()` call that calls `_modified_update()` which updates the modified to a `datetime.datetime.today()` (which should've been `Date(datetime.datetime.today()`, but it doesn't matter for this case here). This can be prevented by removing the `<recurring_term>None</recurring_term>` line in the tasks file.

The parameter passed to `set_modified()` tries to [parse the string as an `datetime.date` first](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/core/dates.py#L140-L145=).

So for some reason, in the XML file for an task `<modified>2022-07-08</modified>` (or similar) is in there and `<term>None</term>` is missing. I am not sure why, probably some migration from v0.5.

The fix should either be using `dt_by_accuracy(Accuracy.datetime)` in untouchedTasks, or just always return an datetime in `get_modified()` (especially since fuzzy dates and different datetime formats aren't useful there).

(Also, it seems to do it at startup when the "Automatically check for untouched tasks" checkbox in the plugin preferences is checked)

**Comment by nekohayo** [comment]
> I will try your suggestion, but with Flatpak's present problem affecting apps like GThumb and Dolphin as well I am not too optimistic. I had to go back to the Ubuntu versions of those as well.

Probably the snap stored your data (config, XML data file, etc.) in a different place, I don't know where. But you can see [this part](https://github.com/getting-things-gnome/gtg/blob/master/README.md#where-is-my-user-data-and-config-stored=) of the GTG "README" file to see what are the standard paths where the flatpak package expects your data to be in.

As for overriding Flatpak's sandboxing with your own custom settings, you can use https://flathub.org/apps/details/com.github.tchx84.Flatseal … but you shouldn't need to. Just make sure your data is in the right folders where flatpak expects them, GTG wouldn't need to see the rest of your filesystem otherwise.

So try that, and editing your config to disable the untouched tasks plugin first, and see if that works around the problem...
