### ISSUE TITLE
Sudden error

### ISSUE THREAD

**Issue by sashinexists** [getting-things-gnome/gtg#922]
When I open GTG I'm greeted with a dialogue telling me to paste the following to an error report

I hope this is useful

```
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/browser/main_window.py", line 733, in on_task_expanded
    sender.expand_node(child_path)
  File "/app/lib/python3.9/site-packages/liblarch_gtk/__init__.py", line 234, in expand_node
    self.collapse_node(llpath, collapsing_method=self.expand_one_row)
  File "/app/lib/python3.9/site-packages/liblarch_gtk/__init__.py", line 258, in collapse_node
    for path in self.basetree.get_paths_for_node(node_id):
  File "/app/lib/python3.9/site-packages/liblarch/viewtree.py", line 188, in get_paths_for_node
    return self._tree.get_paths_for_node(node_id)
  File "/app/lib/python3.9/site-packages/liblarch/filteredtree.py", line 431, in get_paths_for_node
    raise Exception(
Exception: 676f38bc-52b6-47d6-af82-8ca51037bc0d is not children of 8f685c6a-11d6-4094-9d5c-3f12defc414e

Current tree:
root_active
	 parents: []
	 children: ['a7c2fe4d-e0b4-444e-8119-e51142766b05', '31b0257d-16b2-4dec-bc6b-68c6d9b0094e', 'e8f6f1a7-195f-4452-a3cd-f49ab73a8a4c', '29d812c3-a9c9-4812-b0a0-c26ac8f31bb2', 'f4c006b5-09bd-4d65-ae0f-2cfc4fae0aa6', '2b2b0dc7-b27d-4b3d-be22-76f46a437f6a', '1bf584a5-294a-4ec8-b5b8-167324b763ba', '73674a93-39e0-4553-a857-1622b9020a60', '929ccad3-33d8-483b-92c1-d2e112dad8a0', '4dca8d1a-8bdf-47c8-b702-926d5f5b79ce', '263b2e4e-18d5-4644-9246-b5e560b911a7', '770c04e8-33e4-4d80-8ff7-5a987bff4023', 'eb54839b-d34b-468d-ab4a-05459c668167', '3298659e-677f-4f0b-adc1-230a19f9b7d7', '7dd32085-fbff-4d58-a994-cb013e11ad7e', '5fa0859e-6f8e-4bd1-908d-0438421038e7', '752bf137-2956-40ad-a9ef-d964c7875236', '4108a141-4e5c-46ed-8f53-541a04e2f5b8', '0c5fc6bd-0031-4a52-90de-028e934ee27d', '6e827e38-2511-4939-9ad4-d8c71697bd87', 'a536dda7-ef12-41b4-9dd0-7b93fddb9034', '1535ea5e-a291-47bd-b1e5-e64069cc66df', 'edd19eee-c160-4614-a80f-24eedb835a41', 'f31b428e-a5ac-4206-b601-c7120d6aa1f8', '34397468-4b97-48ce-81e5-6c0e3c58de77', 'e3d73bfd-9160-434f-8726-9f3c06de8962', '7020dc54-9be7-4b5f-b2e2-fdd4b87882f1', '07b6d3b5-30e8-46bd-9348-122670e73cd2', '4dc15a37-8ce3-46ba-ba8f-208a13fada37', 'fd1ca967-b5a3-477a-a869-ebaa8c105281', 'd7ec20e8-7780-4a3e-950a-868f48b78bfa', '89e63496-7c89-4bf7-bb58-ceeab627f29e', 'df13b4b6-44e2-4afb-bc56-ccbd2fcc9d13', '3435697e-d315-4fce-a6ea-73aa9397d6f2', '5d27bcec-691c-45fd-a249-6657ca00a0c3', '19b0c0aa-d262-4651-b09e-451385a80383', '87ac5dea-24dc-4abc-af9f-c7c9b98422ea', '7eb902f6-9d4c-4a9e-b9a7-6f430c9a79a8', '78053500-7581-43ad-b001-2a3fc6b9b675', '31d14ac8-5943-48e7-9c29-214d7389e7c5', 'afeca408-6736-4328-bfcf-84f67c5151a0', '843a0e53-985a-4d29-b9da-1059ef726ae2', 'aea77942-6a71-40a2-8877-b859668e4204', '55b4ba80-0bb9-416e-828a-2ec6c9e48463', 'c6db5a0c-3232-4134-8cd9-1dc5d80c4d1b', 'f72b344e-444d-49a7-bddd-37ebd1d0e7ad', '5b22cd52-ee18-4757-9921-9730fe24a7b0', '5543adff-6fe4-49bb-a80a-7cd250637871', '476ff692-f5d5-419a-81b7-226406a83599', 'ee1915ce-672c-4711-ae2a-71231bae41e8', '4fbc4b29-aff1-4db9-a85a-5b3da8557ab0', 'df36bf2f-3df5-4ab8-bf47-ebe420b368bb', '308c1478-255e-440d-9ebd-454538a216b6', '2ab64886-692e-4527-8f3b-17505c2760e9', '2b1c098e-1a63-4013-b1a0-43a0ddbb0789', 'f0147581-60f2-47f4-9b4b-68deb8721ae7', 'db88ff8b-0778-47e0-b734-8fc6e01b5c03', '71439563-32da-457e-9a06-7fa4420cadc9', '7101af22-7df2-4c21-bebc-93a454aa25b8', '78015b3c-72fc-4745-a0a3-7719ef724512', '90cf0b9a-dd52-4aa5-9938-bbce11f9b585', '2ea746f7-c8f0-4eda-a94d-280217a91302', 'e8a43b17-1396-427e-90ae-cf205636f3c1', '173db4ff-069e-430f-9d4c-7dd4b0dd0ad8', '4c24417f-872c-41fb-979f-9cf4a6fdcd02', '679409f7-8221-4abd-86fe-31a7ffe75c83', 'dbcd80ac-ba9e-438d-8f11-32327a892d4a', 'f2066ae1-1d8a-4c83-821a-f96d049b4931', 'f946e706-14ab-4571-b761-baad41685185', 'cc391873-8f99-4e7c-b434-203033313433', '8d3f5153-0517-42ee-95cd-2707a3f5ab14', 'd9ad151c-3a33-4259-9dc3-214e8eddf6c0', '6d9fa8b4-81c2-4b9b-8eae-be25d415d432', 'a5ae7858-70ca-44b6-b6b5-42e6590be902', '63bcc6a6-f9ec-4baf-a1e6-18636b3378df', '6959de63-c4d9-4135-b790-b92e77b4547c', '2f18d6e7-a922-4c6a-8303-a7c152e3381f', 'dc558713-62e1-44cb-aeb9-38bc47c66080', 'c13a212e-a45b-48d9-a926-428e4629457f', 'bab1d03a-d89a-488a-b389-2502cb2b8d3e', 'ca41cbef-deed-47f3-902f-9f6f6e3c0aae', '8055a8bb-2efb-4da5-96d0-60f4f1dc8473', '20e4d4a9-088c-49b2-9af8-7edb1f7135b1', '61605654-2e54-4b7e-b94f-06472f2509fd', 'ecd28d97-bcc6-4181-950a-532fc17f3c65', 'a6104fa1-025b-4ab4-9558-e2b6d257427a', 'a970d0f7-5757-4122-ad24-d43f668d11d6', '56e86d9c-844a-4531-95b7-cf80007fb80c', '8f685c6a-11d6-4094-9d5c-3f12defc414e']
a7c2fe4d-e0b4-444e-8119-e51142766b05
	 parents: ['root_active']
	 children: []
31b0257d-16b2-4dec-bc6b-68c6d9b0094e
	 parents: ['root_active']
	 children: ['13aa1854-ceaa-4a8a-926b-a695a72eb176', '70e31313-ff20-45f1-bd89-f07e39f23f1a', 'fa5614ad-7246-4670-be25-b66277f87185']
13aa1854-ceaa-4a8a-926b-a695a72eb176
	 parents: ['31b0257d-16b2-4dec-bc6b-68c6d9b0094e']
	 children: []
70e31313-ff20-45f1-bd89-f07e39f23f1a
	 parents: ['31b0257d-16b2-4dec-bc6b-68c6d9b0094e']
	 children: []
fa5614ad-7246-4670-be25-b66277f87185
	 parents: ['31b0257d-16b2-4dec-bc6b-68c6d9b0094e']
	 children: []
e8f6f1a7-195f-4452-a3cd-f49ab73a8a4c
	 parents: ['root_active']
	 children: ['140dd639-e1d2-4916-85db-a2b9abb94640']
140dd639-e1d2-4916-85db-a2b9abb94640
	 parents: ['e8f6f1a7-195f-4452-a3cd-f49ab73a8a4c']
	 children: []
29d812c3-a9c9-4812-b0a0-c26ac8f31bb2
	 parents: ['root_active']
	 children: []
f4c006b5-09bd-4d65-ae0f-2cfc4fae0aa6
	 parents: ['root_active']
	 children: ['0b786f16-069e-4665-a897-7e342a5fe861', '177b1e51-8a8b-4668-918b-a8b3716085fe']
0b786f16-069e-4665-a897-7e342a5fe861
	 parents: ['f4c006b5-09bd-4d65-ae0f-2cfc4fae0aa6']
	 children: []
177b1e51-8a8b-4668-918b-a8b3716085fe
	 parents: ['f4c006b5-09bd-4d65-ae0f-2cfc4fae0aa6']
	 children: []
2b2b0dc7-b27d-4b3d-be22-76f46a437f6a
	 parents: ['root_active']
	 children: []
1bf584a5-294a-4ec8-b5b8-167324b763ba
	 parents: ['root_active']
	 children: []
73674a93-39e0-4553-a857-1622b9020a60
	 parents: ['root_active']
	 children: []
929ccad3-33d8-483b-92c1-d2e112dad8a0
	 parents: ['root_active']
	 children: ['0145a625-4596-4bd9-81d7-a54c44709b73']
0145a625-4596-4bd9-81d7-a54c44709b73
	 parents: ['929ccad3-33d8-483b-92c1-d2e112dad8a0']
	 children: []
4dca8d1a-8bdf-47c8-b702-926d5f5b79ce
	 parents: ['root_active']
	 children: []
263b2e4e-18d5-4644-9246-b5e560b911a7
	 parents: ['root_active']
	 children: ['f26a298e-d2b4-46c6-b0a1-03784875ba81', '3f40427d-f4a9-4d8c-93d0-e79d5e325e49', '6069f51b-e9da-45e6-bca1-7a0456a6a5a4', 'cbdc2ad0-9e25-484a-b367-8c9a040ffcca', '108d6d4c-b28e-481d-8a80-af1dc6662665', '721d3826-d78a-4da5-ace2-a41228e38eca']
f26a298e-d2b4-46c6-b0a1-03784875ba81
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
3f40427d-f4a9-4d8c-93d0-e79d5e325e49
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
6069f51b-e9da-45e6-bca1-7a0456a6a5a4
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
cbdc2ad0-9e25-484a-b367-8c9a040ffcca
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
108d6d4c-b28e-481d-8a80-af1dc6662665
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
721d3826-d78a-4da5-ace2-a41228e38eca
	 parents: ['263b2e4e-18d5-4644-9246-b5e560b911a7']
	 children: []
770c04e8-33e4-4d80-8ff7-5a987bff4023
	 parents: ['root_active']
	 children: []
eb54839b-d34b-468d-ab4a-05459c668167
	 parents: ['root_active']
	 children: []
3298659e-677f-4f0b-adc1-230a19f9b7d7
	 parents: ['root_active']
	 children: []
7dd32085-fbff-4d58-a994-cb013e11ad7e
	 parents: ['root_active']
	 children: []
5fa0859e-6f8e-4bd1-908d-0438421038e7
	 parents: ['root_active']
	 children: ['24d9ee75-991f-40d3-92db-87bf24d72bdc', '1337fd57-60f3-4934-93fd-25e2e9c867be']
24d9ee75-991f-40d3-92db-87bf24d72bdc
	 parents: ['5fa0859e-6f8e-4bd1-908d-0438421038e7']
	 children: []
1337fd57-60f3-4934-93fd-25e2e9c867be
	 parents: ['5fa0859e-6f8e-4bd1-908d-0438421038e7']
	 children: ['3070e34f-afa1-4d1d-952a-e5877a4de1d8']
3070e34f-afa1-4d1d-952a-e5877a4de1d8
	 parents: ['1337fd57-60f3-4934-93fd-25e2e9c867be']
	 children: []
752bf137-2956-40ad-a9ef-d964c7875236
	 parents: ['root_active']
	 children: ['f1c047bc-69d9-4e06-91d7-53ea28ba96f5']
f1c047bc-69d9-4e06-91d7-53ea28ba96f5
	 parents: ['752bf137-2956-40ad-a9ef-d964c7875236']
	 children: ['d7ca2652-3b6c-4b71-b8ed-523d1eba69ee']
d7ca2652-3b6c-4b71-b8ed-523d1eba69ee
	 parents: ['f1c047bc-69d9-4e06-91d7-53ea28ba96f5']
	 children: []
4108a141-4e5c-46ed-8f53-541a04e2f5b8
	 parents: ['root_active']
	 children: ['f8ed2fce-9827-405f-acc7-9d253964a9d3']
f8ed2fce-9827-405f-acc7-9d253964a9d3
	 parents: ['4108a141-4e5c-46ed-8f53-541a04e2f5b8']
	 children: []
0c5fc6bd-0031-4a52-90de-028e934ee27d
	 parents: ['root_active']
	 children: ['231b4d54-f944-4010-8eb9-f02a3490307b', '90d9560b-da9f-4b02-943d-03b9ff72112f']
231b4d54-f944-4010-8eb9-f02a3490307b
	 parents: ['0c5fc6bd-0031-4a52-90de-028e934ee27d']
	 children: []
90d9560b-da9f-4b02-943d-03b9ff72112f
	 parents: ['0c5fc6bd-0031-4a52-90de-028e934ee27d']
	 children: []
6e827e38-2511-4939-9ad4-d8c71697bd87
	 parents: ['root_active']
	 children: []
a536dda7-ef12-41b4-9dd0-7b93fddb9034
	 parents: ['root_active']
	 children: []
1535ea5e-a291-47bd-b1e5-e64069cc66df
	 parents: ['root_active']
	 children: []
edd19eee-c160-4614-a80f-24eedb835a41
	 parents: ['root_active']
	 children: []
f31b428e-a5ac-4206-b601-c7120d6aa1f8
	 parents: ['root_active']
	 children: []
34397468-4b97-48ce-81e5-6c0e3c58de77
	 parents: ['root_active']
	 children: ['c7c7e7c0-33db-4dde-852a-a53b2902ee48', '420f6435-02d0-4f45-a4d6-46ba1e7e3ebd', 'f1ba722f-b90f-4444-8a91-9bffd0a1c4ef', 'b46ba87f-42db-4471-9c10-023355a60e66', '2358cdb9-94f1-4fd5-9517-429fa1872698']
c7c7e7c0-33db-4dde-852a-a53b2902ee48
	 parents: ['34397468-4b97-48ce-81e5-6c0e3c58de77']
	 children: []
420f6435-02d0-4f45-a4d6-46ba1e7e3ebd
	 parents: ['34397468-4b97-48ce-81e5-6c0e3c58de77']
	 children: []
f1ba722f-b90f-4444-8a91-9bffd0a1c4ef
	 parents: ['34397468-4b97-48ce-81e5-6c0e3c58de77']
	 children: []
b46ba87f-42db-4471-9c10-023355a60e66
	 parents: ['34397468-4b97-48ce-81e5-6c0e3c58de77']
	 children: []
2358cdb9-94f1-4fd5-9517-429fa1872698
	 parents: ['34397468-4b97-48ce-81e5-6c0e3c58de77']
	 children: []
e3d73bfd-9160-434f-8726-9f3c06de8962
	 parents: ['root_active']
	 children: []
7020dc54-9be7-4b5f-b2e2-fdd4b87882f1
	 parents: ['root_active']
	 children: ['8dd4e6b5-b0a9-406d-964b-e9ffd1edf4dd', '46a27eca-5294-4f56-a37c-63410ea19f89', 'a846f8ee-f9f3-4566-bb81-a43cb475b44d', '98cf9363-9531-4c39-ae23-171fab575f45', 'e2a03298-c388-4723-af41-b2b5658e9c71']
8dd4e6b5-b0a9-406d-964b-e9ffd1edf4dd
	 parents: ['7020dc54-9be7-4b5f-b2e2-fdd4b87882f1']
	 children: []
46a27eca-5294-4f56-a37c-63410ea19f89
	 parents: ['7020dc54-9be7-4b5f-b2e2-fdd4b87882f1']
	 children: []
a846f8ee-f9f3-4566-bb81-a43cb475b44d
	 parents: ['7020dc54-9be7-4b5f-b2e2-fdd4b87882f1']
	 children: []
98cf9363-9531-4c39-ae23-171fab575f45
	 parents: ['7020dc54-9be7-4b5f-b2e2-fdd4b87882f1']
	 children: ['9ea3f910-0b08-4fa2-94f1-869167a80690']
9ea3f910-0b08-4fa2-94f1-869167a80690
	 parents: ['98cf9363-9531-4c39-ae23-171fab575f45']
	 children: []
e2a03298-c388-4723-af41-b2b5658e9c71
	 parents: ['7020dc54-9be7-4b5f-b2e2-fdd4b87882f1']
	 children: []
07b6d3b5-30e8-46bd-9348-122670e73cd2
	 parents: ['root_active']
	 children: ['2e83de49-f672-43f3-a96d-c77a58b59eda']
2e83de49-f672-43f3-a96d-c77a58b59eda
	 parents: ['07b6d3b5-30e8-46bd-9348-122670e73cd2']
	 children: ['eabd5f3c-ff22-46f4-975c-5ce48327c849']
eabd5f3c-ff22-46f4-975c-5ce48327c849
	 parents: ['2e83de49-f672-43f3-a96d-c77a58b59eda']
	 children: []
4dc15a37-8ce3-46ba-ba8f-208a13fada37
	 parents: ['root_active']
	 children: []
fd1ca967-b5a3-477a-a869-ebaa8c105281
	 parents: ['root_active']
	 children: ['60539b83-b0d9-478a-a442-8dd88c7d40ef', '35f352dd-996d-42cf-b8f5-731f6add6433', '78edbcb5-1815-4013-8a8f-0a2fcaf0f9cf', '7a3f13b3-1d32-4dda-9036-85771cbec53b']
60539b83-b0d9-478a-a442-8dd88c7d40ef
	 parents: ['fd1ca967-b5a3-477a-a869-ebaa8c105281']
	 children: []
35f352dd-996d-42cf-b8f5-731f6add6433
	 parents: ['fd1ca967-b5a3-477a-a869-ebaa8c105281']
	 children: []
78edbcb5-1815-4013-8a8f-0a2fcaf0f9cf
	 parents: ['fd1ca967-b5a3-477a-a869-ebaa8c105281']
	 children: []
7a3f13b3-1d32-4dda-9036-85771cbec53b
	 parents: ['fd1ca967-b5a3-477a-a869-ebaa8c105281']
	 children: []
d7ec20e8-7780-4a3e-950a-868f48b78bfa
	 parents: ['root_active']
	 children: ['42afd9c0-f0dd-491c-885e-6007e3354014']
42afd9c0-f0dd-491c-885e-6007e3354014
	 parents: ['d7ec20e8-7780-4a3e-950a-868f48b78bfa']
	 children: ['8d636d35-bbbf-4074-a45f-cd9109d3a084']
8d636d35-bbbf-4074-a45f-cd9109d3a084
	 parents: ['42afd9c0-f0dd-491c-885e-6007e3354014']
	 children: ['66146d36-cc51-405a-b1cd-66ff45f0f8f7']
66146d36-cc51-405a-b1cd-66ff45f0f8f7
	 parents: ['8d636d35-bbbf-4074-a45f-cd9109d3a084']
	 children: ['1e06f33d-6b34-4522-80d8-b58b51bad1bc']
1e06f33d-6b34-4522-80d8-b58b51bad1bc
	 parents: ['66146d36-cc51-405a-b1cd-66ff45f0f8f7']
	 children: []
89e63496-7c89-4bf7-bb58-ceeab627f29e
	 parents: ['root_active']
	 children: ['9949c983-ce51-429a-9f43-e5a19515574f', 'ee196535-fb45-4870-983c-59f2b3557f49', '0e524add-4449-4dcb-850a-981e0f2716fc', '4c7d2bbc-f2db-4f62-8beb-9268f141c4a1', 'ffc1b59d-d2c1-47a1-a9ac-a28d724ed4df', '87f7d983-aaf7-4a7c-8313-361b5f80e0c3', '4ecb3813-d4f5-4a7b-8e62-a5c8fb6f39a2']
9949c983-ce51-429a-9f43-e5a19515574f
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
ee196535-fb45-4870-983c-59f2b3557f49
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
0e524add-4449-4dcb-850a-981e0f2716fc
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
4c7d2bbc-f2db-4f62-8beb-9268f141c4a1
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
ffc1b59d-d2c1-47a1-a9ac-a28d724ed4df
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
87f7d983-aaf7-4a7c-8313-361b5f80e0c3
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
4ecb3813-d4f5-4a7b-8e62-a5c8fb6f39a2
	 parents: ['89e63496-7c89-4bf7-bb58-ceeab627f29e']
	 children: []
df13b4b6-44e2-4afb-bc56-ccbd2fcc9d13
	 parents: ['root_active']
	 children: []
3435697e-d315-4fce-a6ea-73aa9397d6f2
	 parents: ['root_active']
	 children: []
5d27bcec-691c-45fd-a249-6657ca00a0c3
	 parents: ['root_active']
	 children: []
19b0c0aa-d262-4651-b09e-451385a80383
	 parents: ['root_active']
	 children: []
87ac5dea-24dc-4abc-af9f-c7c9b98422ea
	 parents: ['root_active']
	 children: []
7eb902f6-9d4c-4a9e-b9a7-6f430c9a79a8
	 parents: ['root_active']
	 children: []
78053500-7581-43ad-b001-2a3fc6b9b675
	 parents: ['root_active']
	 children: []
31d14ac8-5943-48e7-9c29-214d7389e7c5
	 parents: ['root_active']
	 children: []
afeca408-6736-4328-bfcf-84f67c5151a0
	 parents: ['root_active']
	 children: []
843a0e53-985a-4d29-b9da-1059ef726ae2
	 parents: ['root_active']
	 children: []
aea77942-6a71-40a2-8877-b859668e4204
	 parents: ['root_active']
	 children: ['67b7d1c6-5e99-4a44-937e-770f30ba2c1b', '9b923dce-eb25-4f3f-8676-dd0f6f9bf02c', 'f76f7456-1494-4fca-b92b-841bebb3a6cc']
67b7d1c6-5e99-4a44-937e-770f30ba2c1b
	 parents: ['aea77942-6a71-40a2-8877-b859668e4204']
	 children: []
9b923dce-eb25-4f3f-8676-dd0f6f9bf02c
	 parents: ['aea77942-6a71-40a2-8877-b859668e4204']
	 children: []
f76f7456-1494-4fca-b92b-841bebb3a6cc
	 parents: ['aea77942-6a71-40a2-8877-b859668e4204']
	 children: []
55b4ba80-0bb9-416e-828a-2ec6c9e48463
	 parents: ['root_active']
	 children: []
c6db5a0c-3232-4134-8cd9-1dc5d80c4d1b
	 parents: ['root_active']
	 children: []
f72b344e-444d-49a7-bddd-37ebd1d0e7ad
	 parents: ['root_active']
	 children: ['2346ed50-3023-49ec-880e-6f010897589f', '1c6ac33f-440a-494b-985d-119d6b22585e', 'e72f4736-04f8-4807-bb42-5679f5233909', '2739deb9-a498-4186-aeb8-6790a54b7f1d', 'c0c20085-2729-43fb-8d69-00d06b2b6107', 'e25be0f5-d3f7-432f-ab1d-5de5a45dfd78', '27975f30-8c00-47cd-8927-dbe5cf0df037']
2346ed50-3023-49ec-880e-6f010897589f
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
1c6ac33f-440a-494b-985d-119d6b22585e
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
e72f4736-04f8-4807-bb42-5679f5233909
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
2739deb9-a498-4186-aeb8-6790a54b7f1d
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
c0c20085-2729-43fb-8d69-00d06b2b6107
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
e25be0f5-d3f7-432f-ab1d-5de5a45dfd78
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
27975f30-8c00-47cd-8927-dbe5cf0df037
	 parents: ['f72b344e-444d-49a7-bddd-37ebd1d0e7ad']
	 children: []
5b22cd52-ee18-4757-9921-9730fe24a7b0
	 parents: ['root_active']
	 children: []
5543adff-6fe4-49bb-a80a-7cd250637871
	 parents: ['root_active']
	 children: []
476ff692-f5d5-419a-81b7-226406a83599
	 parents: ['root_active']
	 children: []
ee1915ce-672c-4711-ae2a-71231bae41e8
	 parents: ['root_active']
	 children: []
4fbc4b29-aff1-4db9-a85a-5b3da8557ab0
	 parents: ['root_active']
	 children: []
df36bf2f-3df5-4ab8-bf47-ebe420b368bb
	 parents: ['root_active']
	 children: []
308c1478-255e-440d-9ebd-454538a216b6
	 parents: ['root_active']
	 children: []
2ab64886-692e-4527-8f3b-17505c2760e9
	 parents: ['root_active']
	 children: []
2b1c098e-1a63-4013-b1a0-43a0ddbb0789
	 parents: ['root_active']
	 children: []
f0147581-60f2-47f4-9b4b-68deb8721ae7
	 parents: ['root_active']
	 children: []
db88ff8b-0778-47e0-b734-8fc6e01b5c03
	 parents: ['root_active']
	 children: []
71439563-32da-457e-9a06-7fa4420cadc9
	 parents: ['root_active']
	 children: []
7101af22-7df2-4c21-bebc-93a454aa25b8
	 parents: ['root_active']
	 children: []
78015b3c-72fc-4745-a0a3-7719ef724512
	 parents: ['root_active']
	 children: []
90cf0b9a-dd52-4aa5-9938-bbce11f9b585
	 parents: ['root_active']
	 children: []
2ea746f7-c8f0-4eda-a94d-280217a91302
	 parents: ['root_active']
	 children: []
e8a43b17-1396-427e-90ae-cf205636f3c1
	 parents: ['root_active']
	 children: []
173db4ff-069e-430f-9d4c-7dd4b0dd0ad8
	 parents: ['root_active']
	 children: []
4c24417f-872c-41fb-979f-9cf4a6fdcd02
	 parents: ['root_active']
	 children: ['ac102e51-d91a-4fa3-8cbe-6a310702d3f0', '87066d38-8287-44bb-aa85-2cb784d59533']
ac102e51-d91a-4fa3-8cbe-6a310702d3f0
	 parents: ['4c24417f-872c-41fb-979f-9cf4a6fdcd02']
	 children: []
87066d38-8287-44bb-aa85-2cb784d59533
	 parents: ['4c24417f-872c-41fb-979f-9cf4a6fdcd02']
	 children: []
679409f7-8221-4abd-86fe-31a7ffe75c83
	 parents: ['root_active']
	 children: []
dbcd80ac-ba9e-438d-8f11-32327a892d4a
	 parents: ['root_active']
	 children: []
f2066ae1-1d8a-4c83-821a-f96d049b4931
	 parents: ['root_active']
	 children: []
f946e706-14ab-4571-b761-baad41685185
	 parents: ['root_active']
	 children: []
cc391873-8f99-4e7c-b434-203033313433
	 parents: ['root_active']
	 children: []
8d3f5153-0517-42ee-95cd-2707a3f5ab14
	 parents: ['root_active']
	 children: []
d9ad151c-3a33-4259-9dc3-214e8eddf6c0
	 parents: ['root_active']
	 children: []
6d9fa8b4-81c2-4b9b-8eae-be25d415d432
	 parents: ['root_active']
	 children: []
a5ae7858-70ca-44b6-b6b5-42e6590be902
	 parents: ['root_active']
	 children: []
63bcc6a6-f9ec-4baf-a1e6-18636b3378df
	 parents: ['root_active']
	 children: []
6959de63-c4d9-4135-b790-b92e77b4547c
	 parents: ['root_active']
	 children: []
2f18d6e7-a922-4c6a-8303-a7c152e3381f
	 parents: ['root_active']
	 children: []
dc558713-62e1-44cb-aeb9-38bc47c66080
	 parents: ['root_active']
	 children: []
c13a212e-a45b-48d9-a926-428e4629457f
	 parents: ['root_active']
	 children: []
bab1d03a-d89a-488a-b389-2502cb2b8d3e
	 parents: ['root_active']
	 children: []
ca41cbef-deed-47f3-902f-9f6f6e3c0aae
	 parents: ['root_active']
	 children: []
8055a8bb-2efb-4da5-96d0-60f4f1dc8473
	 parents: ['root_active']
	 children: []
20e4d4a9-088c-49b2-9af8-7edb1f7135b1
	 parents: ['root_active']
	 children: []
61605654-2e54-4b7e-b94f-06472f2509fd
	 parents: ['root_active']
	 children: []
ecd28d97-bcc6-4181-950a-532fc17f3c65
	 parents: ['root_active']
	 children: []
a6104fa1-025b-4ab4-9558-e2b6d257427a
	 parents: ['root_active']
	 children: []
a970d0f7-5757-4122-ad24-d43f668d11d6
	 parents: ['root_active']
	 children: []
56e86d9c-844a-4531-95b7-cf80007fb80c
	 parents: ['root_active']
	 children: ['96ba8b56-4381-4c03-a8f4-605fc4c71351']
96ba8b56-4381-4c03-a8f4-605fc4c71351
	 parents: ['56e86d9c-844a-4531-95b7-cf80007fb80c']
	 children: []
8f685c6a-11d6-4094-9d5c-3f12defc414e
	 parents: ['root_active']
	 children: ['2b8cc636-5e4e-42fc-acfe-446a9351adf0', '2445c0b4-b0f9-470a-89a9-df73be95952d', '489ca7d8-5de4-4d1f-9678-88f847fb3c19']
2445c0b4-b0f9-470a-89a9-df73be95952d
	 parents: ['8f685c6a-11d6-4094-9d5c-3f12defc414e', '2b8cc636-5e4e-42fc-acfe-446a9351adf0']
	 children: []
2b8cc636-5e4e-42fc-acfe-446a9351adf0
	 parents: ['8f685c6a-11d6-4094-9d5c-3f12defc414e']
	 children: ['2445c0b4-b0f9-470a-89a9-df73be95952d']
676f38bc-52b6-47d6-af82-8ca51037bc0d
	 parents: ['8f685c6a-11d6-4094-9d5c-3f12defc414e', '489ca7d8-5de4-4d1f-9678-88f847fb3c19']
	 children: []
489ca7d8-5de4-4d1f-9678-88f847fb3c19
	 parents: ['8f685c6a-11d6-4094-9d5c-3f12defc414e']
	 children: ['676f38bc-52b6-47d6-af82-8ca51037bc0d']

```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.18.16-200.fc36.x86_64-x86_64-with-glibc2.33
```

**Comment by diegogangl** [comment]
The parent relationship of two tasks broke for some reason. This will take some manual fixing, could you open the `gtg_data.xml` file in a text editor and find the item that has an id of `676f38bc-52b6-47d6-af82-8ca51037bc0d`?

Check here for the location of the xml: https://github.com/getting-things-gnome/gtg#where-is-my-user-data-and-config-stored

**Comment by nekohayo** [comment]
Closed as we did not get a reply and we haven't encountered this issue ourselves.
