### ISSUE TITLE
Issue Report "Internal error"

### ISSUE THREAD

**Issue by Disaster2life** [getting-things-gnome/gtg#924]
I was just creating some tasks and this popped up, and it now seems to do that everytime I press backspace? I haven't restarted GTG yet, but I might after this to see if it persists 
`**Context:**` Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/taskview.py", line 200, in process
    if self.detect_subtasks(text, start):
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/taskview.py", line 302, in detect_subtasks
    parents = task.get_parents()
AttributeError: 'NoneType' object has no attribute 'get_parents'
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.19.6-200.fc36.x86_64-x86_64-with-glibc2.33`

**Comment by Disaster2life** [comment]
Update, I think I fixed it without needing to restart, it seemed that having an open "-" for writing a task without anything next to it except the @ tags at the end of the task and that seemed to be conflicting

**Comment by nekohayo** [comment]
Interestingly enough, I encountered the same sort of issue recently when GTG unexpectedly crashed (for the first time ever) while doing some subtask creation/typing in a task, and I don't know exactly how I triggered it. It somehow didn't end up in any major  problem, though I had to re-write my sub-tasks for it after restarting the app.

If you manage to figure out step-by-step reproduction instructions for this, this would be a good thing to test for when Diego's refactoring changes land in master eventually. Maybe this kind of torture case could even be part of a test suite somehow.

**Comment by scovetta** [comment]
I'm not 100% sure this is the same bug, but it's on the same line, and here's a repro for v0.6:

1. Open GTG. Press [+] to create a new task.
2. Add a sub-task within the window.
3. Add another sub-task under the first one.
4. Indent the second sub-task so it's no longer highlighted.
5. Un-indent the second subtask.
6. Error is triggered.

Video is below:

https://user-images.githubusercontent.com/732166/204119944-45a8061a-39da-48d2-a4c4-a010a3e04fb6.mp4

**Comment by pentux-GitHub** [comment]
Housekeeping pass: the reported traceback relies on get_parents, an API that no longer exists anywhere in the new core's UI code, so this exact crash cannot occur on current master. I'd think it's safe to close as obsolete; a fresh report would be welcome if the indent/unindent steps still misbehave on 0.7 in some other way.

**Comment by pentux-GitHub** [comment]
Follow-up now that #1314 has landed on master. I retested the indent/unindent scenario from scovetta's repro above on current master: no crash, no traceback. The editor's `detect_subtasks` now handles the un-parenting cleanly (it just removes the line from the parent's content), where the old GTK3 code hit `get_parents` on a `None` object.

To be precise about the cause: the crashing code path (`taskview.py` calling `get_parents`) was removed by the GTK4 rewrite, not by #1314 specifically — #1314 hardens XML loading against multi-parent claims, which is a different layer. Either way, this exact crash can no longer occur on 0.7. It seems safe to close as obsolete; a fresh report would be welcome if the indent/unindent steps misbehave in some other way on current master.
