### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by sebasvila** [getting-things-gnome/gtg#940]
GTG stopped at start time with this error report:

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/browser/main_window.py", line 596, in open_task
    self.app.open_task(t)
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 553, in open_task
    editor = TaskEditor(requester=self.req, app=self, task=task,
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/editor.py", line 256, in __init__
    self.refresh_editor()
  File "/app/lib/python3.9/site-packages/GTG/gtk/editor/editor.py", line 536, in refresh_editor
    prevcldate = Date.parse(self.closed_entry.get_text())
  File "/app/lib/python3.9/site-packages/GTG/core/dates.py", line 462, in parse
    raise ValueError(f"Can't parse date '{string}'")
ValueError: Can't parse date '4/11/22'
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.10.0-19-amd64-x86_64-with-glibc2.33

**Comment by nekohayo** [comment]
Hmm, that it stops at startup on this means you would have somehow saved a date in that "D/MM/YY" format instead of [ISO 8601](https://xkcd.com/1179/), so you can probably edit that in your data XML file to correct it.

What puzzles me though is, how is it even possible that GTG saved a date in that format, instead of converting it or discarding it...

Do you remember exactly how you saved such a date and where in the GUI?

**Comment by sebasvila** [comment]
I'm really sorry but I cannot remember nothing special on saving dates here or there. I will try to reproduce the error to obtain more info if possible.

**Comment by pentux-GitHub** [comment]
This still bites on current master, reproduced tonight: a single `<due>not-a-date</due>` in the data file aborts the whole load (`ValueError` raised by `Date.parse` in `from_xml`), and in cascade the exception-catcher dialog itself crashes (`dialog` is None in `_check_exception`), so the user gets no error dialog at all. Reproduction recipe available. This joins the loader-hardening family (#1308/#1309 for unknown statuses, #1307/#1314 for multi-parent claims): a fix following the same tolerant-loader pattern is planned.
