### ISSUE TITLE
KeyError raised when opening recurring task for review

### ISSUE THREAD

**Issue by APCBoston** [getting-things-gnome/gtg#942]
Encountered the following while testing my fix for #870 :+1: 

Created a recurring task, closed it, and attempted to reopen.  It opened, but gave the following traceback:

```Traceback (most recent call last):
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/taskview.py", line 186, in process
    start = self.detect_title()
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/taskview.py", line 531, in detect_title
    self.refresh_cb(title)
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 608, in refresh_editor
    self.light_save()
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 950, in light_save
    self.save()
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 931, in save
    t = self.app.ds.tasks.get(self.task.tid)
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/core/tasks2.py", line 340, in get
    return self.lookup[tid]
KeyError: 'e28c7b9d-3e75-4ae7-9ecb-504aafacbb21'

```

I attempted to acknowledge the error and continue working, but it popped back up every time I tried to interact with the task in question.

**Comment by APCBoston** [comment]
For the moment, I am not able to reproduce this myself.

**Comment by BarbzYHOOL** [comment]
how to reproduce it here https://github.com/getting-things-gnome/gtg/issues/950

**Comment by APCBoston** [comment]
@BarbzYHOOL unfortunately not the same.  Your issue raises an AttributeError, whereas this raises a KeyError -- and at an entirely different place in the code.
