### ISSUE TITLE
Internal error when attempting to enable Hamster Time Tracker Integration

### ISSUE THREAD

**Issue by EyobABN** [getting-things-gnome/gtg#960]
The following error message appears when I try to enable the Hamster integration. Any ideas as to why? I have installed the Hamster app, by the way.

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/plugins.py", line 253, in on_plugin_configure
    plugin.instance.configure_dialog(self.dialog)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 365, in configure_dialog
    self.preferences_dialog.set_transient_for(manager_dialog)
AttributeError: 'HamsterPlugin' object has no attribute 'preferences_dialog'
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.15.0-67-generic-x86_64-with-glibc2.33

**Comment by EyobABN** [comment]
Turns out the issue was because GTG did not have permission to access the D-Bus session bus and is solved by turning it on in Flatseal, as mentioned in a comment in #770.
