### ISSUE TITLE
GTG 0.3 won't launch in Ubuntu 12.04

### ISSUE THREAD

**Issue by jakubbrindza** [getting-things-gnome/gtg#99]
THIS IS A REFERENCED BUG FROM LAUNCHPAD. 
DESCRIPTION BELOW. 
FOR FULL CONVERSATION, LOOK AT https://bugs.launchpad.net/gtg/+bug/1088706 

2012-12-10 13:08:54,219 - WARNING - **init**:**init**:77 - Backend backend_mantis could not be loaded: No module named suds.client
2012-12-10 13:08:54,300 - WARNING - **init**:**init**:77 - Backend backend_twitter could not be loaded: No module named tweepy.models
Traceback (most recent call last):
  File "/usr/bin/gtg", line 85, in <module>
    main()
  File "/usr/bin/gtg", line 81, in main
    sys.exit(gtg.main(options, args))
  File "/usr/share/gtg/GTG/gtg.py", line 120, in main
    manager = Manager(req)
  File "/usr/share/gtg/GTG/gtk/manager.py", line 75, in **init**
    self.browser = TaskBrowser(self.req, self)
  File "/usr/share/gtg/GTG/gtk/browser/browser.py", line 89, in **init**
    self.tv_factory.active_tasks_treeview(self.activetree)
  File "/usr/share/gtg/GTG/gtk/browser/treeview_factory.py", line 332, in active_tasks_treeview
    treeview = self.build_task_treeview(tree,desc)
  File "/usr/share/gtg/GTG/gtk/browser/treeview_factory.py", line 419, in build_task_treeview
    treeview = TreeView(tree,desc)
  File "/usr/lib/python2.7/dist-packages/liblarch_gtk/**init**.py", line 189, in **init**
    self.show()
  File "/usr/lib/python2.7/dist-packages/liblarch_gtk/**init**.py", line 268, in show
    self.basetreemodel.connect_model()
  File "/usr/lib/python2.7/dist-packages/liblarch_gtk/treemodel.py", line 64, in connect_model
    self.tree.get_current_state()
  File "/usr/lib/python2.7/dist-packages/liblarch/viewtree.py", line 138, in get_current_state
    self.**ft.get_current_state()
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 606, in get_current_state
    self.send_add_tree(node_id, self.root_id)
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 267, in send_add_tree
    self.callback('added', node_id, path)
  File "/usr/lib/python2.7/dist-packages/liblarch/filteredtree.py", line 124, in callback
    func(node_id,path)
  File "/usr/lib/python2.7/dist-packages/liblarch/viewtree.py", line 115, in __emit
    func(node_id,path)
  File "/usr/lib/python2.7/dist-packages/liblarch_gtk/treemodel.py", line 140, in add_task
    value = access_method(node)
  File "/usr/share/gtg/GTG/gtk/browser/treeview_factory.py", line 76, in task_tags_column
    tags = node.get_tags()
  File "/usr/share/gtg/GTG/core/task.py", line 653, in get_tags
    tag = self.req.new_tag(tname)
  File "/usr/share/gtg/GTG/core/requester.py", line 170, in new_tag
    return self.ds.new_tag(tagname)
  File "/usr/share/gtg/GTG/core/datastore.py", line 128, in new_tag
    self._add_new_tag(name, tag, self.treefactory.tag_filter, parameters)
  File "/usr/share/gtg/GTG/core/datastore.py", line 117, in _add_new_tag
    self.__tasks.add_filter(name, filter_func, parameters=parameters)
  File "/usr/lib/python2.7/dist-packages/liblarch/__init**.py", line 164, in add_filter
    return self.__fbank.add_filter(filter_name, filter_func, parameters)
  File "/usr/lib/python2.7/dist-packages/liblarch/filters_bank.py", line 111, in add_filter
    self.custom_filters[filter_name] = filter_obj
UnboundLocalError: local variable 'filter_obj' referenced before assignment

**Comment by nekohayo** [comment]
Couldn't find a mantis or twitter plugin/backend in the plugins folder. Presuming this got removed.
Reopen if still an issue with current git master of everything and if people are willing to provide patches.
