### ISSUE TITLE
Hamster Time Tracker Plugin: 'HamsterPlugin' object has no attribute 'preferences_dialog'

### ISSUE THREAD

**Issue by Haris-Nr** [getting-things-gnome/gtg#993]
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/GTG/gtk/plugins.py", line 253, in on_plugin_configure
    plugin.instance.configure_dialog(self.dialog)
  File "/usr/lib/python3/dist-packages/GTG/plugins/hamster/hamster.py", line 365, in configure_dialog
    self.preferences_dialog.set_transient_for(manager_dialog)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HamsterPlugin' object has no attribute 'preferences_dialog'
```

**Software versions:**
* Getting Things GNOME! 0.6.0
* CPython 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
* GTK 3.24.38, GLib 2.78.0
* PyGLib 3.46.0, PyGObject 3.46.0
* Linux-6.5.0-13-generic-x86_64-with-glibc2.38

**Comment by Haris-Nr** [comment]
check

**Comment by nekohayo** [comment]
Needs to be retested with the git `master` version.

Related: #996

**Comment by pentux-GitHub** [comment]
Housekeeping pass: the Hamster plugin was fully ported to the new core in #1287, and the ported code does set up preferences_dialog. The retest nekohayo asked for is effectively answered by the port. I'd think this can be closed; a fresh report on 0.7 would be welcome if anything remains.

**Comment by pentux-GitHub** [comment]
Housekeeping: tested on current master tonight — the Hamster configuration dialog opens fine; the plugin was fully rewritten for the new core in #1287. It seems safe to close.
