### ISSUE TITLE
Excelption during try to modify anything on job with hamster plugin enabled

### ISSUE THREAD

**Issue by piio** [getting-things-gnome/gtg#996]
Hi,

After updating to newest version v0.6-367-g66f91627, during try to modify anything (just at right click on existing task) gtg throws following error:

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/home/piio/.archive/src/gtg/.local_build/install/lib/python3.12/site-packages/GTG/core/plugins/api.py", line 72, in __selection_changed
    func(user_data.get_selection())
  File "/home/piio/.archive/src/gtg/.local_build/install/lib/python3.12/site-packages/GTG/plugins/hamster/hamster.py", line 329, in selection_changed
    if selection.count_selected_rows() == 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'count_selected_rows'
```

I have hamster plugin enabled, in logs there are no more errors connected to hamster itself.

**Comment by pentux-GitHub** [comment]
Housekeeping pass: fixed by the Hamster port to the new core (#1287), the GTK3 count_selected_rows API this traceback relies on is no longer in the plugin code. I'd think it's safe to close as fixed.
